kubeshop/helm-charts

.github/workflows/helm-releaser-api-server.yaml
.github/workflows/helm-releaser-kubetest.yaml
.github/workflows/helm-releaser-operator.yaml
.github/workflows/helm-releaser-postman-executor.yaml
.github/workflows/refresh.yml
api-server/charts/api-server/Chart.yaml
kubetest-operator/charts/kubetest-operator/Chart.yaml
kubetest/charts/kubetest/Chart.yaml
postman-executor/charts/postman-executor/Chart.yaml

Fixing helm charts.

---

.gitignore
api-server/charts/api-server/templates/ingress.yaml
api-server/charts/api-server/values.yaml

feat: Add ingress for api server.

---

kubtest/charts/kubtest/values.yaml

fix: [kubtest] Add api-server ingress values to kubtest values.

---

api-server/charts/api-server/values.yaml
kubtest/charts/kubtest/values.yaml

fix: [api-server-ingress] Add missing slash in path.

---

kubtest-dashboard/charts/kubtest-dashboard/.helmignore
kubtest-dashboard/charts/kubtest-dashboard/Chart.yaml
kubtest-dashboard/charts/kubtest-dashboard/templates/NOTES.txt
kubtest-dashboard/charts/kubtest-dashboard/templates/_helpers.tpl
kubtest-dashboard/charts/kubtest-dashboard/templates/deployment.yaml
kubtest-dashboard/charts/kubtest-dashboard/templates/hpa.yaml
kubtest-dashboard/charts/kubtest-dashboard/templates/ingress.yaml
kubtest-dashboard/charts/kubtest-dashboard/templates/service.yaml
kubtest-dashboard/charts/kubtest-dashboard/templates/serviceaccount.yaml
kubtest-dashboard/charts/kubtest-dashboard/templates/tests/test-connection.yaml
kubtest-dashboard/charts/kubtest-dashboard/values.yaml
kubtest/charts/kubtest/Chart.yaml
kubtest/charts/kubtest/values.yaml

This PR adds kubtest-dashboard to be able to add it on install.
Task: https://github.com/kubeshop/kubtest/issues/341 
-
-

feat: Add kubtest-dashboard.

---

.github/workflows/helm-releaser-dashboard.yaml
kubtest-dashboard/charts/kubtest-dashboard/values.yaml
kubtest/charts/kubtest/values.yaml

Added gh actions workflow for dashboard chart

---

README.md

Added mentioning about Dashboard helm chart.

---

kubtest/charts/kubtest/values.yaml

Added needed quotations

---

api-server/charts/api-server/templates/NOTES.txt
api-server/charts/api-server/templates/ingress.yaml
api-server/charts/api-server/templates/rolebinding.yaml
api-server/charts/api-server/values.yaml
kubtest-dashboard/charts/kubtest-dashboard/templates/NOTES.txt
kubtest-dashboard/charts/kubtest-dashboard/templates/ingress.yaml
kubtest-dashboard/charts/kubtest-dashboard/values.yaml
kubtest/charts/kubtest/values-demo.yaml
kubtest/charts/kubtest/values.yaml

feat:Add possibility to install dashboard locally.

---

kubtest/charts/kubtest/Chart.yaml

Added ability of local development for helm_charts

---

scripts/chart_releaser.sh

Aded logic for release version and not just a patch

---

charts/api-server/templates/ingress.yaml
charts/curl-executor/templates/ingress.yaml
charts/cypress-executor/templates/ingress.yaml
charts/postman-executor/templates/ingress.yaml
charts/testkube-dashboard/templates/ingress.yaml
charts/testkube-operator/future_operator_templates/ingress.yaml

Upgrade api from v1beta1 to v1. TO further upgrade gke to 1.22

---

charts/testkube/values-demo.yaml

This PR...
- 
- Remove protocol from API endpoint.

Remove protocol from api endpoint

---

README.md
charts/api-server/templates/deployment.yaml
charts/api-server/values.yaml
charts/testkube/values-demo.yaml
charts/testkube/values.yaml

Providing possibility to disable telemetry for api-server for users.

---

charts/api-server/Chart.yaml
charts/api-server/templates/rolebinding.yaml
charts/testkube/Chart.yaml

fixed role binding

---

.github/workflows/helm-releaser-all-charts.yaml

Added handling GH pages errors or issues.

---

charts/api-server/templates/deployment.yaml
charts/testkube/values.yaml

@fog1985 I messed up the previous PR so I reopened it here.
Signed-off-by: Jasmin Gacic <jasmin.gacic@gmail.com>

added storage values to api-server

---

charts/api-server/values.yaml

Signed-off-by: Jasmin Gacic <jasmin.gacic@gmail.com>

Added missing values

---

.github/workflows/helm-releaser-all-charts.yaml

Aded env variable for skipping existing releases

---

charts/api-server/templates/minio.yaml

Added 1 more port (API) for minio service

---

charts/api-server/templates/deployment.yaml
charts/api-server/values.yaml
charts/testkube/values-demo.yaml
charts/testkube/values.yaml

Fixed storage endpoint

---

charts/api-server/templates/minio.yaml

Added Api 9000 port to minio.

---

charts/api-server/templates/deployment.yaml

Signed-off-by: Jasmin Gacic <jasmin.gacic@gmail.com>
-
-
-

fixed env var from STORAGE_STORAGE_ACCESSKEYID to STORAGE_ACCESSKEYID

---

charts/api-server/values.yaml
charts/testkube/values.yaml

Added description of possibility to turn off minio if needed.

---

charts/kusk-gateway-envoyfleet/templates/envoyFleet.yaml
charts/kusk-gateway/README.md
charts/kusk-gateway/templates/deployment.yaml
charts/kusk-gateway/templates/poddisruptionbudget.yaml
charts/kusk-gateway/templates/rolebinding.yaml
charts/kusk-gateway/templates/roles.yaml
charts/kusk-gateway/templates/service.yaml
charts/kusk-gateway/templates/serviceaccount.yaml
charts/kusk-gateway/templates/webhooks.yaml

Fixes to documentation, make possible to generate yaml file from Helm template.
-
-
-

clarify documentation, fixes for kubectl yaml generation from Helm

---

charts/kusk-gateway/Chart.yaml
charts/kusk-gateway/charts/kusk-gateway-crds/Chart.yaml

Fixes to the correct docker image tag
-
-
-

Fix kusk-gateway appVersion

---

charts/kusk-gateway/Chart.yaml
charts/kusk-gateway/charts/kusk-gateway-crds/Chart.yaml

Fix  dependency for kusk-gateway

---

charts/testkube/values-dashboard.yaml

fix: update demo values and add dashboard values

---

charts/testkube/values-demo.yaml

fix(demo): remove executions from demo ingress path.

---

charts/api-server/Chart.yaml
charts/api-server/templates/role.yaml
charts/api-server/templates/rolebinding.yaml
charts/testkube-operator/Chart.yaml
charts/testkube-operator/crds/tests.testkube.io_tests.yaml
charts/testkube/Chart.yaml

fix: tests roles bindings

---

charts/testkube/values-dashboard.yaml

feat: expose all the endpoints from the api in dashboard

---

charts/testkube/Chart.yaml

fix: chart.yaml indentation

---

charts/api-server/Chart.yaml
charts/api-server/values.yaml
charts/testkube-operator/Chart.yaml
charts/testkube-operator/crds/tests.testkube.io_scripts.yaml
charts/testkube-operator/crds/tests.testkube.io_tests.yaml
charts/testkube-operator/values.yaml
charts/testkube/Chart.yaml

Signed-off-by: Jasmin Gacic <jasmin.gacic@gmail.com>
-
-
-

fix: added missing changes to CRDs

---

charts/testkube/Chart.yaml

Fixed indentation erorr.

---

charts/testkube/Chart.yaml
scripts/chart_releaser.sh

Fixing indentation issue.

---

charts/testkube-operator/Chart.yaml
charts/testkube-operator/crds/executor.testkube.io_executors.yaml
charts/testkube/Chart.yaml
charts/testkube/templates/executors.yaml

fix: helm removed volumes artifacts

---

charts/testkube/values-dashboard.yaml
charts/testkube/values.yaml

fix: use empty string for api server endpoint var

---

charts/api-server/templates/role.yaml
charts/api-server/templates/rolebinding.yaml

closes kubeshop/testkube#798
-
-
-

fix: cluster roles for scripts

---

.github/CODEOWNERS
charts/api-server/templates/role.yaml
charts/api-server/templates/rolebinding.yaml

fix: role for scripts delete all

---

charts/testkube-dashboard/values.yaml

fix: set ingress.enabled to bool instead of string

---

charts/api-server/templates/role.yaml
charts/api-server/templates/rolebinding.yaml

Add cluster roles for managing secrets
-
-
-

feat: add cluster role for secret management

---

.github/workflows/helm-releaser-testkube-charts.yaml

Add secret cleanup for github workflow test suite
-
-
- Add secret cleanup for github workflow test suite

fix: add secrets cleanup for test suite

---

charts/testkube/values.yaml

Allow to run local dashboard
-
- Enable dashboard service for default values
-

feat: allow to run local dashboard

---

.github/workflows/helm-releaser-testkube-charts.yaml
charts/api-server/templates/role.yaml
charts/api-server/templates/rolebinding.yaml
charts/testkube-operator/templates/role.yaml
charts/testkube-operator/templates/tests.testkube.io_scripts.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml

- Add crds for tests v2 and testsuites v1
- Add cluster roles and role bindings
-
-
-

feat: add new crd for test and testsuites

---

.github/workflows/helm-releaser-testkube-charts.yaml
charts/api-server/templates/role.yaml
charts/api-server/templates/rolebinding.yaml
charts/testkube-operator/templates/role.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml

This reverts commit be1d92c07c7870d7be4ef6a0713c493d77bc76af.
-
-
-

feat: return back renaming changes

---

charts/api-server/templates/minio.yaml
charts/api-server/values.yaml
charts/testkube-dashboard/values.yaml
charts/testkube-operator/values.yaml
charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values.yaml

closes https://github.com/kubeshop/testkube/issues/757
-
-
-

feat: ClusterIP instead of NodePort

---

charts/api-server/executors.json

Add init executor record
-
-
-

feat: add executor init record

---

charts/api-server/job_template.yml
charts/api-server/templates/deployment.yaml
charts/testkube-operator/templates/executor.testkube.io_executors.yaml

Pass default job spec from hem chart 
-
-
-

feat: pass job spec

---

charts/api-server/job_template.yml

Tne command for job template
-
-
-

fix: tune command for job template

---

charts/kusk-gateway-envoyfleet/Chart.yaml
charts/kusk-gateway-envoyfleet/values.yaml
charts/kusk-gateway/Chart.yaml
charts/kusk-gateway/charts/kusk-gateway-crds/templates/gateway.kusk.io_envoyfleet.yaml
charts/kusk-gateway/templates/_helpers.tpl
charts/kusk-gateway/templates/deployment.yaml
charts/kusk-gateway/templates/service.yaml
charts/kusk-gateway/templates/webhooks.yaml
charts/kusk-gateway/values.yaml

Adds related to Mocking Kusk Gateway changes (kubeshop/kusk-gateway/#41)
-
-
-

Kusk-gateway-41

---

charts/kusk-gateway/Chart.yaml

Bump kusk-gateway version to new alpha v0.0.0-alpha.2.1.3

---

charts/kusk-gateway/Chart.yaml

Bump kusk-gateway chart

---

charts/api-server/job_template.yml

Change job spec ttl field
-
-
-

fix: update ttl job field

---

charts/api-server/templates/deployment.yaml
charts/api-server/values.yaml
charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values.yaml

feat: add analytics enabled env var

---

charts/api-server/templates/role.yaml
charts/api-server/templates/rolebinding.yaml
charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml

added webhooks crd

---

.github/workflows/helm-releaser-testkube-charts.yaml

fix: sanity test suite fixes

---

charts/testkube-operator/templates/role.yaml
charts/testkube/Chart.yaml

fix: testkube operator roles

---

.github/workflows/helm-releaser-testkube-charts.yaml

Switch to organization CI_BOT_TOKEN
-
-
-

fix: switch to ci bot token

---

charts/api-server/templates/rolebinding.yaml

Remove hardcoded testkube
-
-
-

fix: remove hardcoded testkube name

---

charts/api-server/executors.json

feat: added k6 executor

---

charts/api-server/templates/deployment.yaml
charts/api-server/values.yaml
charts/testkube/Chart.yaml
charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values.yaml

feat: allow mongodb dsn from secrets

---

.github/workflows/helm-releaser-testkube-charts.yaml

feat: updated tests to new dir structure from testkube

---

charts/testkube-api/executors.json

feat: add SoapUI executor

---

charts/testkube-api/templates/minio.yaml
charts/testkube-api/values.yaml
charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values.yaml

Add tolerations, nodeselector and affinity for minio
-
-
-

feat: add tolerations, nodeselector and affinity for minio

---

charts/testkube-api/values.yaml
charts/testkube-dashboard/templates/oauth2-deployment.yaml
charts/testkube-dashboard/templates/oauth2-ingress.yaml
charts/testkube-dashboard/templates/oauth2-service.yaml
charts/testkube-dashboard/values.yaml
charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values.yaml

Dashboard github oauth config
-
-
-

feat: dashboard github oauth config

---

charts/testkube/README.md

fix: update readme

---

charts/testkube-api/values.yaml
charts/testkube-dashboard/values.yaml
charts/testkube/README.md
charts/testkube/values.yaml

Empty annotations for oauth
-
-
-

fix: empty annotations for oauth

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values.yaml

feat: add env vars for slack

---

charts/testkube-api/executors.json

fix: update soapui test types

---

charts/kusk-gateway-api/README.md
charts/kusk-gateway-api/templates/NOTES.txt
charts/kusk-gateway-dashboard/README.md
charts/kusk-gateway-dashboard/templates/NOTES.txt

Closes https://github.com/kubeshop/kusk-gateway/issues/308

Documentation on installing the kusk gateway API and Dashboard

---

charts/tracetest/Chart.yaml
charts/tracetest/templates/deployment.yaml
charts/tracetest/values.yaml

add env variables to enable analytics on tracetest
-
-
-

feat: add env variables to enable analytics on tracetest

---

charts/testkube-api/templates/role.yaml

fix: executor rbac update

---

charts/tracetest/templates/configmap.yaml
charts/tracetest/templates/deployment.yaml
charts/tracetest/values.yaml

Update the tracetest configmap to include the new GA values so it matches the expected format in the app.

update configmap to include ga settings

---

.github/workflows/helm-deploy-testkube-charts-stage.yaml
.github/workflows/helm-releaser-testkube-charts-stage.yaml

Deploy to stage k8s cluster

---

charts/testkube/values-demo.yaml

fix: allow test creation

---

.github/workflows/helm-releaser-testkube-charts.yaml

replaced expired GH token

---

charts/testkube/values-stage.yaml

Sync ingress api for staging
-
-
-

fix: sync ingress api for staging

---

charts/testkube-operator/templates/executor.testkube.io_executors.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml

feat: added variables to Test and TestSuite CRDs

---

charts/testkube-api/executors.json

feat: added content types to executors

---

charts/testkube-api/executors.json

feat: added Artillery.io executor

---

.github/CODEOWNERS
.github/workflows/helm-deploy-testkube-charts-stage.yaml

fix: variables instead of params when calling test suite

---

charts/testkube/Chart.yaml

fix: fix testkube chart version

---

charts/testkube-api/executors.json

fix: artillery type typo

---

.github/workflows/helm-deploy-testkube-charts-stage.yaml

Fix an image tag that is passed from executor repo
-
-
-

fix in executor image tag

---

.github/workflows/helm-releaser-testkube-charts.yaml
charts/testkube/values-demo.yaml

fix: add demo oauth uri

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

fix: use provider oauth parameter

---

README.md
charts/testkube-api/templates/servicemonitor.yaml
charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

closes kubeshop/testkube#1581
-
-
-

fix: service monitor moved to testkube-api and fixed selectors

---

.github/workflows/helm-deploy-testkube-charts-stage.yaml

- added concurrency for github workflow
- added additional changes for `helm` deployment
-
-
-

Update STAGE GH flow

---

.github/workflows/helm-deploy-testkube-charts-stage.yaml

Fix chart error

---

charts/testkube-api/executors.json

fix: test executors update

---

charts/testkube-api/executors.json
charts/testkube/values-demo.yaml

fix: update testkube api

---

charts/testkube-api/executors.json
charts/testkube/values-demo.yaml

fix: remove test

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

feat: remove SLACK_CHANNEL_ID env var as it is detected automatically

---

charts/testkube/Chart.yaml

feat: mongo update

---

charts/testkube/Chart.yaml

feat: mongo chart v11

---

.github/workflows/helm-deploy-testkube-charts-stage.yaml
.github/workflows/helm-releaser-testkube-charts.yaml

fix: demo test fix

---

charts/tracetest/templates/configmap.yaml
charts/tracetest/values.yaml

Add new telemetry settings to configmap.
-
-
-

Add tracetest telemetry values to configmap

---

charts/tracetest/templates/service.yaml
charts/tracetest/values.yaml

Add annotations to tracetest service so it's easier to configure cloud vendor settings

Tracetest: add service annotations

---

charts/kusk-gateway-api/templates/clusterrole.yaml

closes https://github.com/kubeshop/kusk-gateway/issues/421 and closes https://github.com/kubeshop/kusk-gateway/issues/397

add namespace get, list, and watch permission to api-server clusterrole

---

charts/testkube-api/executors.json

feat: kubepug-executor

---

charts/tracetest/templates/configmap.yaml
charts/tracetest/values.yaml

Add polling configuration to chart
-
-
-

feat: add pooling config

---

charts/testkube-operator/templates/deployment.yaml

I noticed that the operator didn't support these fields to be read in from the values file and it would be great to be able to customize them

Support nodeSelectors, affinity, and tolerations

---

.github/workflows/helm-deploy-testkube-charts-stage.yaml
.github/workflows/helm-releaser-testkube-charts.yaml

feat: disabled telemetry for demo and stag clusters

---

charts/tracetest/Chart.yaml

fix: bump tracetest chart version

---

charts/testkube-api/executors.json

feat: added Gradle executor

---

charts/testkube-api/executors.json

feat: added Maven executor

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml

commit field for repository crd
-
-
-

feat: commit field for repository crd

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml

fix: remove depth

---

charts/tracetest/Chart.yaml
charts/tracetest/templates/configmap.yaml
charts/tracetest/values.yaml

Change the way tracetest configuration is setup
- This configuration is invalid for apps with version <= 0.5.6
- Change configuration schema for telemetry

tracetest: setup new configuration schema

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml

add executor args to Test CRD
-
-
-

feat: add executor args to Test CRD

---

charts/kusk-gateway/templates/deployment.yaml
charts/kusk-gateway/templates/service.yaml
charts/kusk-gateway/values.yaml

Add auth service to kusk-gateway
Tested with:
```
helm lint .
helm install --generate-name --dry-run --debug kusk-gateway
```
-
-
-

add auth service to kusk gateway

---

charts/testkube-api/executors.json

feat: add ginkgo executor

---

charts/testkube-api/executors.json

add features to ginkgo updated release
-
-
-

feat: add features to ginkgo updated release

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

support endpoint for s3 bucket
-
-
-

feat: support endpoint for s3 bucket

---

.github/workflows/helm-releaser-testkube-charts.yaml

Use Testkube github action
-
-
-

feat: use Testkube github action

---

charts/testkube/Chart.yaml

fix: new version of mongo securityContext by default

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml

feat: git secrets for Test

---

charts/testkube-api/templates/configmap.yaml
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml

feat: configmap server config

---

charts/kusk-gateway-envoyfleet/Chart.yaml

bump envoyfleet chart version to reflect the bump in envoy image version to 1.23.0
-
-
-

bump envoyfleet chart version

---

charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml

feat: add selector field to webhook

---

charts/kusk-gateway/Chart.yaml

PR where I forgot to bump the version https://github.com/kubeshop/helm-charts/pull/238

bump chart version after adding checksum annotation to deployment

---

charts/testkube-operator/values.yaml
charts/testkube/values.yaml

Initial resource requests for core resources (based on running multiple dozen resource-hungry tests, mainly K6 - 2 GETs without loop delay). They should improve testkube's responsivness under high load. Initial values - the goal is to adjust them over time.
```
No load:
NAME                                                   CPU(cores)   MEMORY(bytes)   
testkube-api-server-77d68fb5fc-gnpvg                   1m           10Mi            
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi             
testkube-minio-testkube-64cd475b94-glxxg               1m           96Mi            
testkube-mongodb-6c9c5db4d5-4hr92                      52m          159Mi           
testkube-operator-controller-manager-7788959c5-ddqml   2m           17Mi …
```

Initial resource requests for core resources

---

charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

fix: port name typo

---

charts/kusk-gateway-api/Chart.yaml
charts/kusk-gateway-api/templates/clusterrole.yaml

allow api to update or patch apis

---

charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

feat: websockets for testkube events

---

charts/kusk-gateway-api/Chart.yaml
charts/kusk-gateway-api/templates/clusterrole.yaml

Signed-off-by: jasmingacic <jasmin.gacic@gmail.com>

Added missing verbs for kusk-manager-api clusterrole

---

charts/kusk-gateway/Chart.yaml
charts/kusk-gateway/crds/gateway.kusk.io_envoyfleet.yaml

Signed-off-by: jasmingacic <jasmin.gacic@gmail.com>

Envoy default image

---

charts/kusk-gateway-api/Chart.yaml
charts/kusk-gateway-api/templates/api.yaml

Signed-off-by: jasmingacic <jasmin.gacic@gmail.com>

Kusk openapi fix

---

charts/testkube-api/templates/deployment.yaml
charts/testkube/Chart.yaml
charts/testkube/values.yaml

feat: NATS event bus for Testkube

---

charts/testkube/Chart.yaml
charts/testkube/values.yaml

fix: added NATS with valid values

---

charts/testkube/Chart.yaml
charts/testkube/values.yaml

fix: nats fixes

---

charts/testkube-operator/templates/executor.testkube.io_executors.yaml
charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml
charts/testkube-operator/templates/tests.testkube.io_scripts.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml

fix:change crd comment

---

charts/testkube/Chart.yaml
charts/testkube/templates/pre-upgrade.yaml

Downgrade Mongo charts to stable 11 version from 12.
-
-
-

Downgrade mongo

---

charts/testkube-dashboard/templates/deployment.yaml
charts/testkube-dashboard/values.yaml

feat: rootless dashboard

---

charts/tracetest/templates/deployment.yaml

Remove unused `VERSION` env from deployment
-
-
-

Tracetest: remove version env

---

charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml
charts/testkube-operator/templates/executor.testkube.io_executors.yaml
charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml
charts/testkube-operator/templates/role.yaml
charts/testkube-operator/templates/tests.testkube.io_scripts.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsources.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml

feat: add test source crd and roles

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml

Added files to tests and test suites
-
-
-

feat: add new property to tests and test suites

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml

Rename parameter from config files to copy files after discussion during meeting
-
-
-

feat: rename parameter from config files to copy files

---

charts/tracetest/Chart.yaml
charts/tracetest/values.yaml

Change default tracetest port
-
-
-

tracetest: change default port

---

charts/testkube-api/templates/minio.yaml

fix: minio storage class name

---

charts/testkube-operator/templates/webhook-cert-create.yaml
charts/testkube-operator/templates/webhook-cert-patch.yaml
charts/testkube-operator/values.yaml

Revert and fix changes of bump script replacing wrong tags
-
-
- issues with bump script replacing wrong tags

testkube-operator: rename tag to version for subcomponents

---

charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

fix: nil registry paramter

---

charts/testkube-api/templates/_helpers.tpl
charts/testkube-api/templates/docker-secret.yaml
charts/testkube-api/templates/minio.yaml
charts/testkube-api/values.yaml
charts/testkube-dashboard/templates/_helpers.tpl
charts/testkube-dashboard/templates/docker-secret.yaml
charts/testkube-dashboard/values.yaml
charts/testkube-operator/templates/_helpers.tpl
charts/testkube-operator/templates/deployment.yaml
charts/testkube-operator/templates/docker-secret.yaml
charts/testkube-operator/values.yaml
charts/testkube/templates/_helpers.tpl
charts/testkube/templates/docker-secret.yaml
charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

fix: revert private docker

---

charts/testkube/values-demo.yaml

Updated SSL redirect for demo cluster
-
-
-

update ssl redirect

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values-dashboard.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

feat: add executors parameter

---

charts/testkube-operator/templates/deployment.yaml

Disable operator webhooks
-
-
-

fix: enable webhook var

---

charts/testkube-api/templates/service.yaml
charts/testkube-api/values.yaml
charts/testkube-dashboard/templates/service.yaml
charts/testkube-dashboard/values.yaml
charts/testkube/values.yaml

Add a possibility to specify annotations in services. This can be used for configuring health checks with AWS Ingress Controller. 
-
-
-

Add annotations

---

charts/testkube/values-demo.yaml

fix: allow patch test to set variables for kubecon

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsources.yaml

feat: add working dir for tests

---

charts/testkube-api/templates/minio.yaml
charts/testkube-api/values.yaml
charts/testkube/values.yaml

Put `username` and `password` for minio into `values` file
-
-
-

remove hardcodes from helm charts

---

charts/testkube-api/executors.json

feat: initial JMeter executor

---

charts/testkube-api/values.yaml
charts/testkube-dashboard/values.yaml

Removed hardcoded ingress annotations so that they can be overridden by `values` file as requested by user.

Ingress annotations

---

charts/testkube-api/job-template.yml

fix: syntax for template var

---

charts/testkube-api/job-container-template.yml

fix: mount artifact volume to init container

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml

Part of this Issue: https://github.com/kubeshop/testkube/issues/2308
-
-
-

feat: MongoDB SSL connection

---

charts/testkube-api/job-container-template.yml
charts/testkube-api/job-scraper-template.yml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml

feat: job template extensions

---

charts/testkube-dashboard/templates/oauth2-deployment.yaml
charts/testkube-dashboard/values.yaml
charts/testkube/values.yaml

oauth2 not only for github

---

charts/testkube-api/templates/minio.yaml
charts/testkube-dashboard/templates/oauth2-deployment.yaml
charts/testkube-operator/templates/webhook-cert-create.yaml
charts/testkube-operator/templates/webhook-cert-patch.yaml

Added missing image pull secrets to Deployments and Jobs.

added missing image pull Secrets

---

charts/kusk-gateway-api/templates/clusterrole.yaml

`charts/kusk-gateway-api/templates/clusterrole.yaml`
----------------------------------------------------
Add `secrets` to list of `resources`.
---
Signed-off-by: Mohamed Bana <mohamed@bana.io>

`kusk-gateway-api`: Allow listing, watching and getting of `secrets`

---

charts/kusk-gateway-dashboard/Chart.yaml
charts/kusk-gateway-dashboard/templates/staticroute.yaml
charts/kusk-gateway/Chart.yaml
charts/kusk-gateway/crds/gateway.kusk.io_staticroutes.yaml

Update `cmd/kusk/manifests/dashboard_staticroute.yaml` to new structure of `StaticRoute`.
Signed-off-by: Mohamed Bana <mohamed@bana.io>

StaticRoute: add `upstream` and remove `paths` from top-level

---

charts/testkube-operator/templates/tests/test-connection.yaml

removed unnecessary line that made kuztomise fail
-
-
-

removed unnecessary line that made kuztomise fail

---

charts/testkube-operator/templates/webhook-cert-patch.yaml
charts/testkube-operator/values.yaml

Added node tolerations for webhook job
-
-
-

add node tolerations to cert patch

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml

feat: add prerun script

---

charts/testkube-api/templates/role.yaml

feat: add configmaps for watching

---

charts/tracetest/values.yaml

pin pg version to 14

---

charts/testkube-api/templates/minio.yaml
charts/testkube-api/templates/tests/test-connection.yaml
charts/testkube-api/values.yaml
charts/testkube-dashboard/templates/tests/test-connection.yaml
charts/testkube-operator/templates/deployment.yaml
charts/testkube-operator/templates/tests/test-connection.yaml
charts/testkube-operator/templates/webhook-cert-create.yaml
charts/testkube-operator/values.yaml
charts/testkube/templates/pre-upgrade.yaml
charts/testkube/values.yaml

Allowed resource specifications for missing components. 
-
-
-

allow resource specifications

---

charts/testkube-api/templates/servicemonitor.yaml

fix identation in servicemonitor

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml

feat: scraper template field

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values.yaml

Part of https://github.com/kubeshop/testkube/issues/2497
-
-
-

feat: add possibility to specify bucket for logs storage

---

charts/testkube-api/templates/role.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml

feat: test and test suite status

---

charts/testkube-api/templates/tests/test-connection.yaml
charts/testkube-dashboard/templates/tests/test-connection.yaml
charts/testkube-operator/templates/deployment.yaml
charts/testkube-operator/values.yaml
charts/testkube/values.yaml

Added resource option for kube-proxy container.
-
-
-

add resource to kube-proxy container

---

charts/testkube-operator/templates/rolebinding.yaml

update leader election role name with a variable

---

charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml
charts/testkube-api/values.yaml
charts/testkube-operator/templates/executor.testkube.io_executors.yaml
charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml
charts/testkube-operator/templates/tests.testkube.io_scripts.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsources.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml
charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml
charts/testkube-operator/values.yaml
charts/testkube/values-demo.yaml
charts/testkube/values.yaml

feat: Allow to install Testkube Cloud agent into several namespaces 

---

charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml

feat: test trigger conditions

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsources.yaml

Related to https://github.com/kubeshop/testkube/issues/2136
-
-
-

feat: add certificate secret to the test and testsource CR

---

charts/testkube-api/templates/deployment.yaml

fix: proper allow disk use parameter

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsources.yaml

fix: make certificate secret string

---

charts/testkube-api/job-container-template.yml
charts/testkube-api/job-template.yml

Related to https://github.com/kubeshop/testkube/issues/2136
-
-
-

fix: update job template with cert volumes

---

charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml

testkube-operator: new testtrigger crd which supports delay and printcolumns

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml

Related to https://github.com/kubeshop/testkube/issues/2482
-
-
-

feat: add negativeTest to test CRD

---

charts/testkube-api/templates/_helpers.tpl
charts/testkube-api/values.yaml
charts/testkube/values.yaml

Added override option for NATS URI.
-
-
-

provide override for NATS URI

---

.github/workflows/helm-releaser-testkube-charts.yaml

Updated main workflow so that it is triggered only from other repositories dispatch action.
-
-
-

update helm releaser flow

---

charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml

feat: testtigger condition reason field

---

charts/testkube-api/executors.json

feat: add Playwright executor to Testkube

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

Related to https://github.com/kubeshop/testkube/issues/2940
-
-
-

feat: add bucket env var for storing artifact in a single bucket

---

charts/testkube-operator/templates/webhook-cert-create.yaml

Update security context for `migrate` container.
-
-
-

update security context

---

charts/testkube-api/executors.json

fix: rename content types

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml

feat: mark envs deprecated

---

.github/workflows/helm-deploy-testkube-charts-stage.yaml
.github/workflows/helm-releaser-testkube-charts.yaml
.github/workflows/helm-releaser-testkube-main-chart-only.yaml

I added the records to Cloudflare, just pending merge of testkube repo PR: https://github.com/kubeshop/testkube/pull/3194
Signed-off-by: Abdallah Abedraba <aabedraba@gmail.com>
-
-
-

fix: change testkube install.sh location

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

-
- With this PR you have the posibility to put the slack token in a secret and avoid commit this in a repository for security concerns.
-

feat: Add posibility to put the slack token in a secret 

---

charts/testkube-api/job-container-template.yml
charts/testkube-api/job-template.yml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml

feat: envs for secret and config map

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-dashboard/templates/deployment.yaml
charts/testkube-dashboard/values.yaml
charts/testkube-operator/templates/deployment.yaml
charts/testkube-operator/values.yaml
charts/testkube/values.yaml

Since we cannot change container Port for our services, it has been decided to hardcode them. Our users find it confusing to leave the ports as a variable. 
-
-
-

Hardcode dashboard port

---

charts/testkube/values.yaml

Reverts kubeshop/helm-charts#406

fix: Revert "update path for api"

---

charts/testkube-api/executors.json
charts/testkube-operator/templates/executor.testkube.io_executors.yaml

feat: add git type

---

charts/testkube-api/templates/configmap.yaml
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/templates/hpa.yaml
charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml
charts/testkube-api/values.yaml

Load config files from configmap
-
-
-

testkube-api: load files from configmap

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml

testkube-api: fix for testkube-api deployment envvars

---

charts/testkube-operator/templates/deployment.yaml
charts/testkube-operator/templates/service.yaml

testkube-operator: fix wrong ports for webhooks

---

charts/testkube-api/templates/minio.yaml

Add security Context for Minio.
-
-
-

add security context for minio

---

charts/testkube/values.yaml

Fix: https://github.com/kubeshop/testkube/issues/3402
-
-
-

fix: missing context initialization

---

charts/testkube/values.yaml

testkube: fix backwards compatibility issue due to label update

---

charts/testkube-api/templates/minio.yaml

testkube-api: fix duplicate securityContext in MinIO

---

charts/testkube/README.md

Add a warning about the bug with labels that prevented successful upgrade.
-
-
-

update installation docs with warning

---

charts/testkube/templates/pre-upgrade.yaml
charts/testkube/values.yaml

Add an option to override mongodb upgrade image.
-
-
-

update image for mongodb upgrade pod

---

scripts/chart_releaser.sh

feat: monorepo

---

charts/tracetest/Chart.yaml

[tracetest] fix incorrect RC version update

---

charts/tracetest/values.yaml

[tracetest]: update provisioning

---

charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml

feat: payload object field

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

Related to https://github.com/kubeshop/testkube/issues/3226
-
-
-

feat: add region to minio

---

charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml

Fix https://github.com/kubeshop/helm-charts/issues/450
-
-
-

Testkube: enable cors preflight requests on the api ui ingress

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml

Related to https://github.com/kubeshop/testkube/issues/3116
-
-
-

feat: docdb with tls

---

charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

Update values to change NATS maxPayload value

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

Related to https://github.com/kubeshop/testkube/issues/3218
-
-
-

feat: add expiration for minio storage

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml

https://github.com/kubeshop/testkube/issues/3140
-
-
-

feat: mongo ssl cert secret keys configurable

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/templates/service.yaml
charts/testkube-api/values.yaml

Update service port and probes for TK API
-
-
-

update port and probes for testkube-api

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml

https://github.com/kubeshop/testkube/issues/3329
-
-
-

feat: configurable http body size limit

---

charts/testkube-api/job-container-template.yml
charts/testkube-api/job-scraper-template.yml
charts/testkube-api/job-template.yml
charts/testkube-api/templates/deployment.yaml

fix: pass registry param to api

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values-demo.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

fix: rename parameter

---

charts/testkube-api/executors.json

fix: add git-dir to jmeter

---

charts/tracetest/Chart.yaml
charts/tracetest/templates/deployment.yaml

Fix tracetest dev env var

---

charts/global/templates/_capabilities.tpl
charts/testkube-api/templates/hpa.yaml
charts/testkube-dashboard/templates/hpa.yaml

update autoscaling for the api and dashboard
-
-
-

update autoscaling for the api and dashboard

---

charts/testkube-api/templates/configmap.yaml
charts/testkube-api/values.yaml
charts/testkube/values.yaml

Related to https://github.com/kubeshop/testkube/issues/3630
-
-
-

feat: add possibility to configure slack from helm values

---

.github/workflows/helm-deploy-testkube-charts-develop.yaml

fix a typo

---

charts/testkube-operator/cronjob-template.yml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml

feat: cron job template field

---

charts/tracetest/templates/deployment.yaml
charts/tracetest/templates/service.yaml
charts/tracetest/values.yaml

Updating Tracetest chart to centralize server ports and change deployment and services to use it.

Fixing tracetest ports

---

charts/testkube-api/executors.json

Added beta tags as a temp solution since it's a new repository without release ones. Will push them later.
-
-
-

fix executors.json

---

.github/workflows/helm-deploy-testkube-charts-develop.yaml
.github/workflows/helm-deploy-testkube-charts-stage.yaml

rework flow to deploy api and executors

---

scripts/chart_releaser.sh

Edited script.sh to include two options: 
- editing chart versions and executors
- editing only chart versions
-
-
-

edit script for updating chart versions

---

charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-pre-release.yaml
charts/testkube/values-stage.yaml

Update POST request for `/results/v1/repositories`
-
-
-

Fix post request in nginx config

---

.github/workflows/helm-deploy-testkube-charts-develop.yaml
.github/workflows/helm-deploy-testkube-charts-pre-release.yaml
.github/workflows/helm-deploy-testkube-charts-stage.yaml

Commit executors image tag to develop every time they are updated because they are re-written by dashboard and operator deployment. 
-
-
-

commit executor image tag to develop

---

scripts/chart_releaser.sh

Update naming for release branch to release/$service/$tag
-
-
-

ci: update naming for release branch

---

scripts/chart_releaser.sh

update release branch naming 
-
-
-

update release branch naming

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-pre-release.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

feat: cdevents support

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-pre-release.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

feat: dashboard uri for cd events

---

.github/workflows/helm-deploy-testkube-charts-develop.yaml
.github/workflows/helm-deploy-testkube-charts-pre-release.yaml
.github/workflows/helm-deploy-testkube-charts-stage.yaml
charts/testkube-api/executors.json
scripts/chart_releaser.sh

WIP - will be ready once the docker image is prepared
-
-
-

feat: zap executor

---

.github/workflows/helm-deploy-testkube-charts-pre-release.yaml

Update tests with develop branch.
-
-
-

ci: update tests

---

charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml

feat: condition ttl

---

scripts/chart_releaser.sh

Add automatic PR creation from release to main branch.
-
-
-

ci: add automatic pr creation

---

.github/workflows/helm-deploy-testkube-charts-develop.yaml
.github/workflows/helm-deploy-testkube-charts-pre-release.yaml
.github/workflows/helm-deploy-testkube-charts-stage.yaml
charts/testkube-api/executors.json

add condition for checking if executors.json were updated
-
CI changes
-

ci: add condition for checking if executors.json were updated

---

charts/testkube/values-stage.yaml

feat: added webhook to cdevents for test purpose

---

charts/testkube-operator/templates/pre-upgrade.yaml
charts/testkube-operator/templates/webhook-cert-create.yaml
charts/testkube-operator/templates/webhook-cert-patch.yaml
charts/testkube/templates/pre-upgrade.yaml
charts/testkube/values.yaml

feat: add TTL for k8s jobs

---

charts/testkube-operator/templates/pre-upgrade.yaml

fix: preupgrade labels

---

charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml

feat: webhook template and headers

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml

See https://discord.com/channels/884464549347074049/1088559756714705067/1088571830639542343

TestKube doc update: preRunScript ignored for container executor

---

charts/testkube-api/templates/minio.yaml

fix: minio service labels

---

charts/testkube-api/templates/deployment.yaml

Fixed error with enabled monfo tls.
-
-
-

fix: error with enabled mongo tls

---

charts/testkube-api/templates/deployment.yaml
charts/testkube/Chart.yaml

Fixed allowTLS option for Mongo.
-
-
-

fix: allow tls for mongo

---

charts/testkube-api/templates/configmap.yaml
charts/testkube-api/values.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-pre-release.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

Added an option to provide custom `job-template.yml`.
From cli: 
```
helm install testkube ./testkube --debug -n testkube --set-file testkube-api.configValues=path/job-template-labels.yaml
```
or just by passing in `values.yml`:
```
testkube-api:
configValues: |
apiVersion: batch/v1
kind: Job
metadata:
name: "{{ .Name }}"
namespace: {{ .Namespace }}
labels:
label1: 1
label2: 2
label3: 3
...etc
```
-
-
-

feat: update config map for testkube-api

---

.github/workflows/helm-releaser-testkube-charts.yaml
.github/workflows/helm-releaser-testkube-main-chart-only.yaml

tests: update branch for checking out tests

---

.github/workflows/helm-deploy-testkube-charts-develop-commit.yaml
.github/workflows/helm-deploy-testkube-charts-develop.yaml
.github/workflows/helm-deploy-testkube-charts-pre-release.yaml
.github/workflows/helm-deploy-testkube-charts-stage.yaml

ci: add arg to run install beta release to test cli

---

scripts/chart_releaser.sh

ci: update releaser script

---

.github/workflows/helm-deploy-testkube-charts-stage-commit.yaml

Added a flow to automatically deploy to Stage cluster when `values-stage.yaml` are updated. Needed for testing during release. 
-
-
-

ci: add flow to deploy to stage on values.yaml update

---

charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml

Add basic auth for testkube-dev and testkube-stage env. removed all ingress restrictions. 
-
-
-

ci: add basic auth

---

charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml

feat: probe conditions

---

.github/workflows/helm-deploy-testkube-charts-develop.yaml
.github/workflows/helm-deploy-testkube-charts-pre-release.yaml
.github/workflows/helm-deploy-testkube-charts-stage.yaml
charts/testkube-api/executors.json
scripts/chart_releaser.sh

feat: tracetest executor

---

charts/testkube/values-pre-release.yaml

feat: add basic auth for beta env

---

charts/testkube-dashboard/templates/deployment.yaml
charts/testkube-dashboard/values.yaml
charts/testkube/README.md
charts/testkube/values-develop.yaml

- add Helm option to select CRD revision for front-end
- use `develop` for dev.testkube.io
-
-
-

feat: add Helm option to select CRD revision for front-end, use develop for dev.testkube.io

---

charts/testkube-api/templates/minio.yaml
charts/testkube/Chart.yaml

Invert logic for minio secrets
-
-
-

Fix: minio secrets

---

.github/workflows/helm-deploy-testkube-charts-develop-commit.yaml
.github/workflows/helm-deploy-testkube-charts-develop.yaml
.github/workflows/helm-deploy-testkube-charts-pre-release.yaml
.github/workflows/helm-deploy-testkube-charts-stage-commit.yaml
.github/workflows/helm-deploy-testkube-charts-stage.yaml
.github/workflows/helm-releaser-testkube-charts.yaml
.github/workflows/helm-releaser-testkube-main-chart-only.yaml

missing namespaces added after removing them from CRDs

Testkube - E2E tests - missing namespaces added

---

charts/testkube-api/templates/deployment.yaml

Fix passing secrets ti API
-
-
-

fix: api secrets logic

---

charts/tracetest/Chart.yaml

fix(charts/tracetest): bump helm chart version

---

charts/testkube/values-develop.yaml

Needed to run tests with vercel preview

Testkube - CORS allow all methods for dev environment

---

charts/testkube-operator/templates/tests.testkube.io_tests.yaml

feat: remove outdated comment

---

.github/workflows/helm-deploy-testkube-charts-stage-commit.yaml
.github/workflows/helm-deploy-testkube-charts-stage.yaml

https://github.com/kubeshop/testkube/pull/4186
https://github.com/kubeshop/helm-charts/pull/583
https://github.com/kubeshop/testkube-dashboard/pull/785

Testkube - integration workflows updated (dashboard-e2e-tests for specific namespace)

---

charts/testkube-dashboard/templates/oauth2-deployment.yaml
charts/testkube-dashboard/values.yaml
charts/testkube/values.yaml

Added an option to provide secrets for aouth env vars
-
-
-

feat: add secrets for oauth

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-pre-release.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

feat: compress artifacts flag

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/templates/minio.yaml
charts/testkube-dashboard/templates/deployment.yaml
charts/testkube-dashboard/templates/oauth2-deployment.yaml
charts/testkube-operator/templates/deployment.yaml
charts/testkube-operator/values.yaml
charts/testkube/templates/pre-upgrade-sa.yaml
charts/testkube/templates/pre-upgrade.yaml
charts/testkube/values.yaml

Propagate global labels to `.spec.template.`
-
-
-

fix global labels

---

charts/testkube-operator/values.yaml
charts/testkube/values.yaml

Update image for testkube operator pre-upgarde job
-
-
-

fix: update image for testkube operator pre-upgrade job

---

.github/workflows/helm-releaser-testkube-main-chart-only.yaml
scripts/main_chart_releaser.sh

revert changes (#593)

---

charts/testkube-api/templates/deployment.yaml
charts/testkube/templates/configmap.yaml

feat: pass helm chart version

---

charts/testkube-operator/templates/pre-upgrade.yaml
charts/testkube-operator/values.yaml
charts/testkube/values.yaml

Add lables values section for testkube-operator preUpgrade webhook job

---

.github/workflows/helm-deploy-testkube-charts-pre-release.yaml

ci: move beta cluster to develop

---

.github/workflows/helm-deploy-testkube-charts-pre-release.yaml

move beta cluster to develop

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/templates/minio.yaml
charts/testkube-api/values.yaml
charts/testkube-dashboard/templates/deployment.yaml
charts/testkube-dashboard/templates/oauth2-deployment.yaml
charts/testkube-dashboard/values.yaml
charts/testkube-operator/templates/deployment.yaml
charts/testkube-operator/values.yaml
charts/testkube/values-demo.yaml
charts/testkube/values.yaml

Added an option to specify priority Class for Deployments. This is also needed for our demo env since we have enabled autoscaling and TK pods need to have priority in scheduling. 
-
-
-

feat: add priority Class

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/templates/minio.yaml
charts/testkube-api/values.yaml
charts/testkube-dashboard/templates/deployment.yaml
charts/testkube-dashboard/templates/oauth2-deployment.yaml
charts/testkube-dashboard/values.yaml
charts/testkube-operator/templates/deployment.yaml
charts/testkube-operator/values.yaml
charts/testkube/values-demo.yaml
charts/testkube/values.yaml

feat: add priority Class (#602)

---

charts/testkube-operator/cronjob-template.yml
charts/testkube-operator/templates/deployment.yaml

fix: image registry

---

charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml
charts/testkube-operator/templates/role.yaml
charts/testkube-operator/templates/tests.testkube.io_testexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuiteexecutions.yaml

feat: test execution crd

---

.github/workflows/helm-releaser-testkube-charts.yaml
.github/workflows/helm-releaser-testkube-main-chart-only.yaml

Disable mongo probes so that resource utilisation will drop.  
-
-
-

ci: disable mongo probes

---

.github/workflows/helm-releaser-testkube-charts.yaml
.github/workflows/helm-releaser-testkube-main-chart-only.yaml

ci: disable mongo probes main

---

charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml
charts/testkube-operator/templates/executor.testkube.io_executors.yaml
charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml
charts/testkube-operator/templates/role.yaml
charts/testkube-operator/templates/tests.testkube.io_templates.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml

feat: template crd

---

charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml

fix: adjust uri description

---

charts/testkube/templates/pre-upgrade.yaml
charts/testkube/values.yaml

add annotations and pod labels for mongo pre-upgrade job
-
-
-

feat: add annotations and pod labels for pre-upgrade job

---

charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml

charts: add priority class; change node selectors

---

.github/workflows/helm-deploy-testkube-charts-develop.yaml
.github/workflows/helm-deploy-testkube-charts-stage.yaml
charts/testkube-api/executors.json
scripts/chart_releaser.sh

feat: added jmeterd

---

charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml

values: update ingress for the api

---

charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml

feat: trigger concurrency policy

---

charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml

values: replace dns name for the ingresses

---

charts/testkube-api/templates/_helpers.tpl
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml
charts/testkube-api/templates/serviceaccount.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values.yaml

testkube-api: add support for tests service account and rbac

---

charts/testkube-operator/templates/executor.testkube.io_executors.yaml
charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml
charts/testkube-operator/templates/tests.testkube.io_scripts.yaml
charts/testkube-operator/templates/tests.testkube.io_templates.yaml
charts/testkube-operator/templates/tests.testkube.io_testexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsources.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuiteexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml
charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml

testkube-api: update CRDs

---

charts/testkube-api/executors.json

testkube-api: update slave config for jmeterd

---

.github/workflows/helm-deploy-testkube-charts-develop.yaml
.github/workflows/helm-deploy-testkube-charts-stage.yaml
scripts/chart_releaser.sh

fix: bash script that updates executors.json

---

charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml

values: disable basic auth for develop and stage

---

artifacthub-repo.yml

feat: artifacthub

---

charts/testkube-api/slack-template.json

feat: slack template

---

charts/testkube-operator/templates/tests.testkube.io_testexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuiteexecutions.yaml

feat: execute post run script before scraping field

---

charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml

values: update priority for mongo

---

charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml

feat: regex field

---

charts/testkube-api/executors.json

fix: add git-dir

---

charts/testkube-api/executors.json

fix: add git-dir (#663)

---

charts/testkube-operator/templates/executor.testkube.io_executors.yaml

feat: data dir as working dir

---

charts/tracetest/Chart.yaml

Bump tracetest version

---

charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml
charts/testkube-operator/values.yaml
charts/testkube/README.md
charts/testkube/values.yaml

fix: add download artifacts option

---

charts/testkube-operator/README.md
charts/testkube-operator/cronjob-template.yml
charts/testkube-operator/templates/deployment.yaml
charts/testkube-operator/values.yaml
charts/testkube/README.md
charts/testkube/values.yaml

feat: use argo cd sync var

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/README.md.gotmpl
charts/testkube/values.yaml

chore: cherry pick nats and minio TLS settings

---

charts/testkube-operator/templates/tests.testkube.io_testsuiteexecutions.yaml

fix: step start and end time

---

charts/testkube-api/README.md
charts/testkube-api/templates/configmap.yaml
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values.yaml

feat: install only specified executors

---

charts/testkube-api/README.md
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values.yaml

feat: add "cloud" ui url

---

.github/workflows/helm-releaser-testkube-charts.yaml
.github/workflows/helm-releaser-testkube-main-chart-only.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml

* Increase storage size in our environments
* Add object expiration in our environments
-
-
-

testkube: increase storage size for our envs and add expiration date

---

charts/testkube/README.md
charts/testkube/values.yaml

testkube: enable jetstream in nats

---

charts/testkube-api/templates/ui-ingress.yaml

Fixes issue mentioned in [684](https://github.com/kubeshop/helm-charts/issues/684)
-
-
-

fix: TK API ingress class name

---

charts/testkube-api/job-scraper-template.yml.tmpl

fix: scraper logs not behind feature flag

---

charts/testkube-logs/templates/deployment.yaml
charts/testkube-logs/values.yaml
charts/testkube/values.yaml

feat: add minio new logs config

---

charts/testkube/values-demo.yaml

fix: demo global values

---

charts/testkube-logs/templates/deployment.yaml

fix: log bucket missing

---

charts/testkube-api/executors.json

fix: reorder jmeter args

---

charts/testkube/values-develop.yaml

Add back password for develop

---

charts/testkube/Chart.yaml

fix: nats version

---

.github/workflows/helm-releaser-testkube-charts.yaml
.github/workflows/helm-releaser-testkube-main-chart-only.yaml
charts/testkube/Chart.yaml

Fix concurrency

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube-logs/README.md
charts/testkube-logs/templates/deployment.yaml
charts/testkube-logs/templates/service.yaml
charts/testkube-logs/templates/tests/test-connection.yaml
charts/testkube-logs/values.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

feat: server log grpc config

---

charts/testkube-operator/templates/tests.testkube.io_testexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuiteexecutions.yaml

fix: replace args mode alias

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

Configuration for https://github.com/kubeshop/testkube/pull/5005
-
-
-

feat: add configuration for persistent image data cache

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube-logs/templates/deployment.yaml
charts/testkube-logs/values.yaml
charts/testkube/values.yaml

feat: grpc client and server tls

---

charts/testkube-logs/templates/deployment.yaml
charts/testkube-logs/values.yaml

fix: added params to the logs service

---

charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml

* Add roles for the Testkube API Server to access the TestWorkflows
-
-
-

feat(TKC-1155): add TestWorkflow RBAC

---

charts/testkube-api/README.md
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

feat: disable secret creation

---

charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml

feat: add execution request to test suite steps

---

charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml

cherry-pick from develop
-
-
-

feat: test suite step params main

---

charts/testkube-operator/templates/deployment.yaml
charts/testkube-operator/values.yaml
charts/testkube/values.yaml

Fixes [753](https://github.com/kubeshop/helm-charts/issues/753)
-
-
-

feat: add an option to pass custom job template to Operator

---

charts/testkube/values-local-enterprise.yaml

feat: simple local enteprise values

---

charts/testkube-api/README.md
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml
charts/testkube-api/templates/serviceaccount.yaml
charts/testkube-api/values.yaml
charts/testkube-logs/templates/deployment.yaml
charts/testkube-operator/templates/tests.testkube.io_testexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuiteexecutions.yaml
charts/testkube/README.md
charts/testkube/values.yaml

feat: execution namespace field

---

charts/testkube-operator/templates/tests.testkube.io_testexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuiteexecutions.yaml

fix: source scripts field

---

charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

Update CRDs to the latest version from the `testkube-operator`

feat: update CRDs

---

charts/testkube-api/job-container-template.yml.tmpl
charts/testkube-api/job-scraper-template.yml.tmpl
charts/testkube-api/job-template.yml.tmpl
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values.yaml

testkube: TKC-1290: add support for custom CA certificates

---

charts/testkube-api/README.md
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml
charts/testkube-api/templates/serviceaccount.yaml
charts/testkube-api/values.yaml
charts/testkube-logs/templates/deployment.yaml
charts/testkube-operator/templates/tests.testkube.io_testexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuiteexecutions.yaml
charts/testkube/README.md
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

feat: Release/v1.16.35

---

charts/testkube-api/Chart.yaml
charts/testkube-api/templates/role.yaml
charts/testkube/Chart.yaml
charts/testkube/values.yaml

Add `deletecollection` for Jobs and Pods

fix: add missing roles for TestWorkflow cleanup

---

charts/testkube-operator/Chart.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml
charts/testkube/Chart.yaml

* Pass down https://github.com/kubeshop/testkube-operator/pull/233

fix: add workingDir to artifacts step

---

charts/testkube-api/Chart.yaml
charts/testkube-api/values.yaml
charts/testkube/Chart.yaml
charts/testkube/README.md
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

* We are using it already for some time on our agents, works well.

feat: enable persistent cache of image details by default

---

.github/workflows/helm-deploy-testkube-charts-develop-commit.yaml
.github/workflows/helm-deploy-testkube-charts-develop.yaml
.github/workflows/helm-deploy-testkube-charts-stage-commit.yaml
.github/workflows/helm-deploy-testkube-charts-stage.yaml

fix: delete dashboard e2e tests

---

.github/configs/ct-lint.yaml
.github/workflows/lint.yaml
charts/testkube-logs/Chart.yaml
charts/testkube-logs/templates/deployment.yaml
charts/testkube-logs/values.yaml
charts/testkube/Chart.yaml
charts/testkube/values-dev-enterprise.yaml
charts/testkube/values-local-enterprise.yaml
charts/testkube/values.yaml

removed logs path, using separate ingress by default

---

.github/workflows/dispatch-develop-push.yaml

Adds dispatch event to the deployment repo.
- Adds dispatch event on push to develop.
- TKC-1752
- TKC-1753

feat: dispatch event to deployments repo on push to develop

---

charts/testkube-api/job-container-template.yml.tmpl
charts/testkube-api/job-scraper-template.yml.tmpl
charts/testkube-api/job-template.yml.tmpl
charts/testkube-api/slave-pod-template.yml.tmpl

feat: slave pod logs

---

charts/tracetest/Chart.yaml
charts/tracetest/templates/deployment.yaml

fix: rollback tracetest healthcheck

---

charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml

fix: add secret list role

---

charts/testkube-api/templates/deployment.yaml

Update the name of the environment variables to *_PRO_* from *_CLOUD_*
-
-
-

fix: update cloud variables to pro

---

charts/testkube-api/job-container-template.yml.tmpl
charts/testkube-api/job-scraper-template.yml.tmpl
charts/testkube-api/job-template.yml.tmpl
charts/testkube-api/pvc-template.yml.tmpl
charts/testkube-api/slave-pod-template.yml.tmpl
charts/testkube/Chart.yaml

fix: allow to override data volume

---

charts/testkube/values-develop.yaml

feat: enable logsV2 for develop env

---

charts/testkube-api/job-container-template.yml.tmpl
charts/testkube-api/job-scraper-template.yml.tmpl
charts/testkube-api/job-template.yml.tmpl
charts/testkube-api/pvc-template.yml.tmpl
charts/testkube-api/slave-pod-template.yml.tmpl
charts/testkube/Chart.yaml

chore: cherry pick to release

---

charts/testkube-api/Chart.yaml
charts/testkube-api/slave-pod-template.yml.tmpl
charts/testkube/Chart.yaml

fix: dont attach init when global data directory used

---

.github/workflows/helm-deploy-testkube-charts-develop-commit.yaml
.github/workflows/helm-deploy-testkube-charts-develop.yaml
.github/workflows/helm-deploy-testkube-charts-stage-commit.yaml
.github/workflows/helm-deploy-testkube-charts-stage.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml

- removes left-overs from the Dashboard
- updates CI for logs-service
-
-
-

ci: fix flow for logs service

---

charts/testkube-api/Chart.yaml
charts/testkube-api/slave-pod-template.yml.tmpl
charts/testkube/Chart.yaml

* fix: dont attach init when global data directory used
* fix update chart version
* fix update chart version
* fix update chart version
* fix linter errors
-
-
-

chore: Cherry pick attach data container

---

charts/testkube-api/Chart.yaml
charts/testkube-api/job-container-template.yml.tmpl
charts/testkube-api/job-scraper-template.yml.tmpl
charts/testkube-api/job-template.yml.tmpl
charts/testkube-api/pvc-template.yml.tmpl
charts/testkube-api/slave-pod-template.yml.tmpl
charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml
charts/testkube/Chart.yaml

feat: Release/v1.17.8

---

charts/testkube-api/job-scraper-template.yml.tmpl
charts/testkube-api/job-template.yml.tmpl
charts/testkube-api/slave-pod-template.yml.tmpl
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values.yaml

Depends on: https://github.com/kubeshop/testkube/pull/5269
-
-
-

feat: inject custom ca

---

charts/testkube-api/job-scraper-template.yml.tmpl
charts/testkube-api/job-template.yml.tmpl
charts/testkube-api/slave-pod-template.yml.tmpl
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values.yaml

* feat: inject custom ca into agent
* feat: custom ca job template
* feat: custom ca job scraper template
* feat: custom ca slave pod template
* fix: set env var to inject ca into runners
-
-
-

feat: inject custom ca (#799)

---

charts/testkube/values.yaml

fix: duplicate custom ca secret ref in parent chart

---

charts/testkube-logs/Chart.yaml

fix: logs version

---

charts/testkube-api/job-container-template.yml.tmpl
charts/testkube-api/job-scraper-template.yml.tmpl
charts/testkube-api/job-template.yml.tmpl
charts/testkube-api/pvc-template.yml.tmpl
charts/testkube-api/slave-pod-template.yml.tmpl
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube-operator/templates/tests.testkube.io_testexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuiteexecutions.yaml
charts/testkube/README.md
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

feat: use default storage class name

---

charts/testkube-operator/Chart.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml
charts/testkube/Chart.yaml

* CRDs from https://github.com/kubeshop/testkube-operator/pull/241

feat(testworkflows): update CRDs to support matrix/shards for execute step

---

charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-local-enterprise.yaml
charts/testkube/values.yaml

fix: removed nats box from depoyment

---

charts/testkube-operator/cronjob-template.yml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

feat: test workflow cron job

---

charts/testkube-api/templates/testworkflows/builtin-templates/serviceaccount.yaml
charts/testkube-api/values.yaml
charts/testkube/values.yaml

* Add `builtin-templates` folder
* Add configuration variables for including the templates

feat(testworkflows): add support for built-in TestWorkflow templates

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/templates/testworkflows/builtin-templates/global-template.yaml
charts/testkube-api/values.yaml
charts/testkube/values.yaml

* Add support for global template that will be automatically used for all executions
* https://github.com/kubeshop/testkube/pull/5311

feat(testworkflows): add support for global TestWorkflowTemplate

---

charts/testkube-api/values.yaml
charts/testkube-operator/templates/testworkflows/builtin-templates/artillery.yaml
charts/testkube-operator/templates/testworkflows/builtin-templates/cypress.yaml
charts/testkube-operator/templates/testworkflows/builtin-templates/global-template.yaml
charts/testkube-operator/templates/testworkflows/builtin-templates/gradle.yaml
charts/testkube-operator/templates/testworkflows/builtin-templates/jmeter.yaml
charts/testkube-operator/templates/testworkflows/builtin-templates/k6.yaml
charts/testkube-operator/templates/testworkflows/builtin-templates/maven.yaml
charts/testkube-operator/templates/testworkflows/builtin-templates/playwright.yaml
charts/testkube-operator/templates/testworkflows/builtin-templates/postman.yaml
charts/testkube-operator/templates/testworkflows/builtin-templates/serviceaccount.yaml
charts/testkube-operator/values.yaml

feat: Release/v1.17.16 - cherry pick f84d0085

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

* https://github.com/kubeshop/testkube-operator/pull/243

chore(testworkflows): update CRDs

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

* https://github.com/kubeshop/testkube-operator/pull/245

feat(testworkflows): add pausing steps

---

charts/testkube-api/templates/deployment.yaml

Cherry pick

---

charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml

feat: add testworkflow for triggers

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

* copy CRDs from https://github.com/kubeshop/testkube-operator/pull/247

feat(testworkflows): support more advanced Pod configuration

---

charts/testkube-api/slack-config.json
charts/testkube-api/slack-template.json.tmpl
charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml
charts/testkube/values.yaml

feat: workflow events

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

feat: namespace for test workflow job config

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

* https://github.com/kubeshop/testkube-operator/pull/252

feat(testworkflows): update CRDs to add activeDeadlineSeconds for job

---

charts/testkube-api/job-container-template.yml.tmpl
charts/testkube-api/job-scraper-template.yml.tmpl
charts/testkube-api/job-template.yml.tmpl
charts/testkube-api/slave-pod-template.yml.tmpl

Only covers pre-built and container executors.
cherry-pick back to develop.
-
-
-

fix: pull from git server with private-ca certs

---

charts/testkube-api/README.md
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml
charts/testkube-api/values.yaml
charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml
charts/testkube/README.md
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

feat: events role

---

charts/testkube-api/templates/testworkflows/builtin-templates/distribute.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

* https://github.com/kubeshop/testkube-operator/pull/253

feat(testworkflows): update CRDs to add parallel step definition

---

charts/testkube-api/templates/minio.yaml
charts/testkube-api/values.yaml
charts/testkube/values.yaml

feat: add minio metrics

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml

* Add support for accompanying services

feat(testworkflows): update CRDs to support accompanying `services`

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml

Release: accompanying services

---

charts/testkube-api/templates/testworkflows/builtin-templates/distribute.yaml

fix: make distribute--evenly installed post install

---

charts/testkube-api/job-container-template.yml.tmpl
charts/testkube-operator/templates/tests.testkube.io_testexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuiteexecutions.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

feat: sidecar scraper option

---

charts/testkube-api/templates/role.yaml

* https://github.com/kubeshop/helm-charts/pull/850
-
-
-

hotfix: add missing patch/update permissions (required for updating ConfigMap of image inspector)

---

charts/testkube/values.yaml

Requested in [831](https://github.com/kubeshop/helm-charts/issues/831)
-
-
-

feat: add setting for readiness and liveness probes for mongodb

---

charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml

Add new field to the webhook CRD
-
-
-

feat: [TKC-1948] disable webhooks

---

charts/testkube-api/templates/role.yaml
charts/testkube-api/templates/rolebinding.yaml
charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml

fix(main): simplify permissions / add disabled property for webhook CRD

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

* https://github.com/kubeshop/testkube-operator/pull/263
-
-
-

fix: update CRD to have services[k].logs as expression condition

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

(cherry picked from commit 59a32e33c7d8702ae927824af7e4e0cfe239643a)
-
-
-

Release: fix: update CRD to have services[k].logs as expression condition (#860)

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

* https://github.com/kubeshop/testkube-operator/pull/268

fix: update CRD to have services[k].description

---

charts/testkube-api/templates/testworkflows/builtin-templates/jmeter.yaml

fix: typo in JMeter template

---

charts/testkube-api/templates/_job-container-template.yaml.tpl
charts/testkube-api/templates/_job-scraper-template.yaml.tpl
charts/testkube-api/templates/_job-template.yaml.tpl
charts/testkube-api/values.yaml
charts/testkube/values.yaml

add support for additional volumes and mounts in test jobs
-
-
-

testkube: add support for additional volumes and mounts in test jobs

---

charts/testkube-operator/templates/tests.testkube.io_testexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuiteexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml

feat: [TKC-1948] disable webhooks on tests and testsuites

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowexecutions.yaml

* https://github.com/kubeshop/testkube-operator/pull/274

fix: update TestWorkflowExecution CRD

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

* https://github.com/kubeshop/testkube-operator/pull/275
-
-
-

feat: ssh keys for git content

---

charts/testkube-api/templates/_job-container-template.yaml.tpl
charts/testkube-api/templates/_job-scraper-template.yaml.tpl
charts/testkube-api/templates/_job-template.yaml.tpl
charts/testkube-api/values.yaml
charts/testkube/values.yaml

feat(testkube-api): ability to specify annotations on job templates

---

charts/testkube-api/templates/_helpers.tpl

Follow up of this commit which broke deployment:
```
commit 06addde626ee6d20eb2fea5191360a5d51fc5182
Author: Emil Davtyan <emil@kubeshop.io>
Date:   Tue Jun 4 10:46:26 2024 +0200
fix: clean up deployment env (#868)
* fix: clean up deployment env
* fix: remove unused oauth env vars
```
-
-
-

fix: rollback nats settings for agent config

---

charts/testkube-api/templates/role.yaml
charts/testkube-operator/templates/tests.testkube.io_testexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuiteexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowexecutions.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

Changes related to the newest release

Release testkube/v1.17.55

---

.github/workflows/helm-releaser-testkube-charts.yaml
.github/workflows/helm-releaser-testkube-main-chart-only.yaml

Pass Testkube OSS Agent version to cloud charts repo on release.
-
-
-

ci: TKC-210-pass-agent-version

---

.github/workflows/helm-releaser-testkube-charts.yaml
.github/workflows/helm-releaser-testkube-main-chart-only.yaml

ci TKC-210-pass-agent-version (#878)

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

feat: [TKC-1948] disable webhooks on workflows

---

charts/testkube-api/templates/_helpers.tpl
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values.yaml

feat: added embedded nats configuration options

---

charts/testkube-api/templates/_helpers.tpl

fix: nats embedded env not existing when nats disabled

---

charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml

feat: disabled trigger flag

---

charts/testkube-api/templates/testworkflows/builtin-templates/beta/artillery.yaml
charts/testkube-api/templates/testworkflows/builtin-templates/beta/cypress.yaml
charts/testkube-api/templates/testworkflows/builtin-templates/beta/gradle.yaml
charts/testkube-api/templates/testworkflows/builtin-templates/beta/jmeter.yaml
charts/testkube-api/templates/testworkflows/builtin-templates/beta/k6.yaml
charts/testkube-api/templates/testworkflows/builtin-templates/beta/maven.yaml
charts/testkube-api/templates/testworkflows/builtin-templates/beta/playwright.yaml
charts/testkube-api/templates/testworkflows/builtin-templates/beta/postman.yaml

Cherry pick wizard label

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values.yaml

feat: testkube: add support for whitelisting container log scraping

---

charts/testkube-api/templates/_job-container-template.yaml.tpl
charts/testkube-api/templates/_job-scraper-template.yaml.tpl
charts/testkube-api/templates/_job-template.yaml.tpl
charts/testkube-api/templates/_slave-pod-template.yaml.tpl
charts/testkube-api/values.yaml
charts/testkube/values.yaml

Add an option to specify resources requests and limits from values.yaml for container templates.
-
-
-

feat: add resource limits and requests for containers

---

charts/testkube-api/values.yaml
charts/testkube/values.yaml

fix: data type

---

charts/testkube-api/templates/_job-container-template.yaml.tpl
charts/testkube-api/templates/_job-scraper-template.yaml.tpl
charts/testkube-api/templates/_job-template.yaml.tpl
charts/testkube-api/templates/_slave-pod-template.yaml.tpl
charts/testkube-api/values.yaml
charts/testkube/values.yaml

fix: add container resources requests limits

---

.github/workflows/dispatch-develop-push.yaml

feat: use github app token

---

.github/workflows/dispatch-develop-push.yaml

feat: use github app token (#905)

---

charts/testkube-api/templates/_helpers.tpl
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values.yaml

feat: testkube: add support for global skip certificate verification

---

charts/testkube-api/templates/_helpers.tpl
charts/testkube-api/templates/_job-container-template.yaml.tpl
charts/testkube-api/templates/_job-scraper-template.yaml.tpl
charts/testkube-api/templates/_job-template.yaml.tpl
charts/testkube-api/templates/_slave-pod-template.yaml.tpl
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values.yaml

Add support for global skipVerify, caPath and volume mounts
-
-
-

cherry-pick: testkube: update global section with tls config

---

charts/testkube-operator/templates/tests.testkube.io_testexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_tests.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuiteexecutions.yaml
charts/testkube-operator/templates/tests.testkube.io_testsuites.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowexecutions.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

feat: refactor webhook disabling

---

.github/workflows/dispatch-sandbox-push.yaml

ci: add sandbox dispatch

---

charts/testkube-api/README.md
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values.yaml

Depends on https://github.com/kubeshop/testkube/pull/5660
-
-
-

testkube: add support for defining image credentials cache ttl

---

.github/workflows/dispatch-sandbox-deletion.yaml

ci: add sandbox deletion

---

charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml

fix: deprecate on state change

---

charts/testkube-operator/README.md
charts/testkube-operator/templates/deployment.yaml
charts/testkube-operator/values.yaml
charts/testkube/README.md
charts/testkube/values-develop.yaml
charts/testkube/values.yaml

fix: purge executions options

---

charts/testkube-operator/README.md
charts/testkube-operator/templates/deployment.yaml
charts/testkube-operator/values.yaml
charts/testkube/README.md
charts/testkube/values-develop.yaml
charts/testkube/values.yaml

fix: purge executions options (#922)

---

charts/testkube-operator/templates/deployment.yaml

fix operator cronjob

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

Release v2.1.0

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowexecutions.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

feat: [TKC-2299] test workflow execution tags

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

feat: [TKC-2308] test workflow sensitive config parameter

---

charts/testkube-operator/values.yaml
charts/testkube/values.yaml

feat: update kube-webhook-certgen image

---

charts/testkube-api/README.md
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/README.md
charts/testkube/values-demo.yaml
charts/testkube/values-develop.yaml
charts/testkube/values-stage.yaml
charts/testkube/values.yaml

Pass docker image version for telemetry and server info
-
-
-

feat: [TKC-2684] docker image version

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

feat: [TKC-2726] cronjob config

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

feat:[TKC-2765]  selector for test workflow execute

---

charts/testkube-api/values.yaml
charts/testkube/values.yaml

fix: update description in values

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

* https://github.com/kubeshop/testkube-operator/pull/309
-
-
-

feat: add `cone` option to `content.git` / fix: reduce size of CRDs

---

charts/testkube-api/values.yaml
charts/testkube/values.yaml

fix: nats uri

---

charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml

feat: [TKC-3102] add generation and resource trigger cause

---

charts/testkube-api/templates/servicemonitor.yaml
charts/testkube-api/values.yaml

feat: add sampleLimit to ServiceMonitor configuration

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/values.yaml

* Add the possibility of passing the Global Template as a YAML string

feat: make it possible to pass YAML string as a global template

---

charts/testkube-api/Chart.yaml
charts/testkube/Chart.yaml

* reflect changes from https://github.com/kubeshop/helm-charts/pull/987

fix: bump testkube-api version

---

charts/testkube-operator/Chart.yaml
charts/testkube/Chart.yaml

fix: bump testkube-operator version

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowexecutions.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml

feat: execution reference

---

README.md
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

This PR contributes to TKC-3197

chore: update TestWorkflow CRD for GitHub App authType enum

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

fix: [TK-3315] remove timeout constraint

---

charts/testkube-operator/templates/deployment.yaml
charts/testkube-operator/templates/service.yaml
charts/testkube-operator/values.yaml
charts/testkube/values.yaml

feat: add an option for insecure metrics port for the operator

---

charts/testkube-operator/templates/deployment.yaml

feat: update posts for the operator

---

charts/testkube-operator/Chart.yaml
charts/testkube-operator/templates/poddisruptionbudget.yaml
charts/testkube/Chart.yaml

fix: add labels pdb

---

charts/testkube-api/values.yaml
charts/testkube/values.yaml

bump: update executors

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

chore: add target to workflow crd

---

charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml

feat: improve probe configurability

---

.github/workflows/helm-releaser-testkube-main-chart-only.yaml

ci: fix getting chart version

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

feat: [TKC-3371]  add env global flag

---

charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowexecutions.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

chore: add targetting

---

charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowexecutions.yaml

This PR contributes to https://linear.app/kubeshop/issue/TKC-3444/add-targeting-to-trigger-execute-and-cron

chore: update crds for targetting

---

charts/testkube-api/README.md
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml
charts/testkube/README.md
charts/testkube/values.yaml

fix: hostpid field

---

charts/testkube-runner/.helmignore
charts/testkube-runner/Chart.yaml
charts/testkube-runner/templates/_helpers.tpl
charts/testkube-runner/templates/deployment.yaml
charts/testkube-runner/templates/poddisruptionbudget.yaml
charts/testkube-runner/templates/role.yaml
charts/testkube-runner/templates/rolebinding.yaml
charts/testkube-runner/templates/serviceaccount.yaml
charts/testkube-runner/values.yaml
scripts/chart_releaser.sh
scripts/image_cve_check.sh
scripts/image_pull_secrets_check.sh
scripts/image_registry_check.sh

* add simpler and safer Helm Chart for Runner Agent

feat: add Helm Chart for testkube-runner

---

charts/testkube-api/values.yaml
charts/testkube-operator/values.yaml
charts/testkube/values.yaml

fix: enable agent cronjob by default

---

.github/workflows/helm-releaser-testkube-main-chart-only.yaml
.github/workflows/helm-releaser-testkube-runner-chart-only.yaml
scripts/runner_chart_releaser.sh

Add new workflow to only release testkube runner when it's changed.
-
-
-

chore: create specific flow to release testkube runner chart

---

charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml

feat: [TKC-3694] cron timezone

---

charts/testkube-api/templates/role.yaml
charts/testkube-runner/templates/role.yaml

Add `patch` verb to runner and api roles.
This is required for setting canceled status for workflow executions.
-
-
-

feat: TKC-3683: Add patch verb to runner and api roles

---

charts/testkube-api/values.yaml

chore: disable gitops agent syncing

---

charts/testkube-api/README.md
charts/testkube-api/templates/_helpers.tpl
charts/testkube-api/templates/deployment.yaml
charts/testkube-api/values.yaml
charts/testkube/Chart.yaml
charts/testkube/README.md
charts/testkube/templates/_helpers.tpl
charts/testkube/values.yaml

feat: [TKC-3759] add postgres support
