- charts/kusk-gateway/Chart.yaml
- charts/kusk-gateway/charts/kusk-gateway-crds/Chart.yaml
- charts/kusk-gateway/templates/webhooks.yaml
Fixes webhook labels.
Bumps to new alpha version.
-
-
-
> Bump kusk-gateway chart version, fix the labels on the webhook

- charts/kusk-gateway-envoyfleet/Chart.yaml
- charts/kusk-gateway-envoyfleet/README.md
- charts/kusk-gateway-envoyfleet/templates/NOTES.txt
- charts/kusk-gateway-envoyfleet/templates/envoyFleet.yaml
- charts/kusk-gateway-envoyfleet/values.yaml
- charts/kusk-gateway/Chart.yaml
- charts/kusk-gateway/charts/kusk-gateway-crds/templates/gateway.kusk.io_apis.yaml
- charts/kusk-gateway/charts/kusk-gateway-crds/templates/gateway.kusk.io_envoyfleet.yaml
- charts/kusk-gateway/charts/kusk-gateway-crds/templates/gateway.kusk.io_staticroutes.yaml
- charts/kusk-gateway/templates/NOTES.txt
- charts/kusk-gateway/templates/certmanagement.yaml
- charts/kusk-gateway/templates/deployment.yaml
- charts/kusk-gateway/templates/roles.yaml
- charts/kusk-gateway/templates/service.yaml
- charts/kusk-gateway/templates/webhooks.yaml
- charts/kusk-gateway/values.yaml
Changes kusk-gateway-manager and kusk-gateway-envoyfleet charts for the upcoming alpha.2 version.
Webhooks are now mandatory since we depend a lot on them.
More documentation.
-
-
-
> Kusk Gateway alpha.2 preparations

- charts/kusk-gateway/values.yaml
Add log level option to kusk-gateway manager args which allows user to set log verbocity.
Add Development boolean option which allows kusk-gateway manager to be run in development mode (logging stack traces on warning logs and panicking on dpanic level logs
-
-
-
> Add log level and development mode options to manager args

- charts/testkube/values-demo.yaml
> fix: generate/renew certificate on dashboard ingress only

- charts/testkube/values-dashboard.yaml
- charts/testkube/values-demo.yaml
Allow only GET for api ingress and POST to run tests and test suites
-
-
-
> fix: allow only GET for api ingress and POST to run tests and test suites

- .github/CODEOWNERS
Taras' username in the CODEOWNERS file caused Github to complain as he is not part of the org anymore.
Also added myself as a code owner
> Update CODEOWNERS: remove Taras and add kylehodgetts

- charts/kusk-gateway-api/templates/clusterrole.yaml
-
- grant create permission on API resources to kusk gateway api clusterrole
- Permission denied when trying to publish an API via the kusk gateway API
> Grant RBAC create API permission to Kusk Gateway API clusterrole

- charts/kusk-gateway/templates/configmap.yaml
Fix error
```
Error: ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found f, error found in #10 byte of ...|ENABLED":false,"ENAB|..., bigger context ...|_MANAGER_BIND_ADDR":":18010","ANALYTICS_ENABLED":false,"ENABLE_LEADER_ELECTION":"false","ENVOY_CONTR|...
```
Boolean for enabling analytics should be passed as a string
related https://github.com/hashicorp/terraform-provider-helm/issues/556#issuecomment-665620365
> Quote config map values

- charts/tracetest/templates/configmap.yaml
- charts/tracetest/values.yaml
Changes the way tracetest handles tracing backend configuration
- Tracetest changed how to configure the backend data storage. This version of the helm will not work with older versions of tracetest.
> enhance: update tracing backend config

- charts/testkube-api/templates/peerauthentication.yaml
Updated `PeerAuthentication` policy to allow either plaintext or mTLS tunnel for the whole `testkube` namespace
-
-
-
> update policy to allow both plaintext or mTLS tunnel

- charts/testkube/values-demo.yaml
Pointed dashboard.testkube.io to `testkube-dev` cluster
https://dashboard.testkube.io/
-
-
-
> add dashboard host to testkube cluster

- charts/kusk-gateway-api/templates/api.yaml
- charts/kusk-gateway-api/templates/service.yaml
We removed the service reconciler from kusk gateway which uses Service annotations to setup the exposure of an API.
This PR removes the annotations from Kusk Gateway API's service definition and in its place, added an API resource.
> Replace KGW service reconciler annotations with API resource.

- charts/kusk-gateway-api/Chart.yaml
- charts/kusk-gateway-api/templates/deployment.yaml
- charts/kusk-gateway-api/values.yaml
- charts/kusk-gateway/Chart.yaml
- charts/kusk-gateway/crds/gateway.kusk.io_envoyfleet.yaml
This PR updates the EnvoyFleet CRD with a new field "default" which denotes whether or not an instance of an EnvoyFleet is the default i.e. if the EnvoyFleet is not specified in an API or Static Route resource, it should be exposed by the default envoy fleet.
Bumped the Kusk Gateway chart version to reflect the changes above.
Bumped the Kusk Gateway API chart version to reflect the changes made in #223 and allowing user to specify whether or not to disable analytics
> Kusk Gateway: Add Default field to EnvoyFleet CRD

- charts/testkube-api/templates/minio.yaml
- charts/testkube-api/values.yaml
- charts/testkube-operator/templates/deployment.yaml
- charts/testkube-operator/values.yaml
- charts/testkube/values-demo.yaml
- charts/testkube/values-stage.yaml
- charts/testkube/values.yaml
Made `minio` and `operator` images customizable. Now they can be overwritten with: `--set` option
-
-
-
> make minio and operator image customizable

- charts/kusk-gateway-api/Chart.yaml
- charts/kusk-gateway-api/templates/api.yaml
- charts/kusk-gateway-dashboard/Chart.yaml
- charts/kusk-gateway-dashboard/templates/staticroute.yaml
Add label kusk-managed: true to managed api and static resource so they are filtered out of api calls.
closes https://github.com/kubeshop/kusk-gateway/issues/581
> Add label kusk-managed: true to managed api and static resource

- charts/kusk-gateway/templates/deployment.yaml
This allows us to easily restart the kusk gateway deployment when the contents of the config map change, e.g. the user disables analytics
relates to https://github.com/kubeshop/kusk-gateway/issues/449
> Add checksum annotation for configmap contents to kusk gateway deployment

- charts/testkube/values.yaml
testkube-api memory request increased to prevent pod OOMKilled under high load
> testkube-api memory request increased to prevent pod OOMKilled

- charts/kusk-gateway-envoyfleet/Chart.yaml
- charts/kusk-gateway-envoyfleet/templates/envoyFleet.yaml
- charts/kusk-gateway-envoyfleet/values.yaml
- charts/kusk-gateway/Chart.yaml
- charts/kusk-gateway/crds/gateway.kusk.io_envoyfleet.yaml
This regenerates the EnvoyFleet CRD and includes the recently added Default field which specifies whether or not this is a default envoyfleet
> Update EnvoyFleet CRD with make manifests in kgw

- charts/tracetest/templates/deployment.yaml
- charts/tracetest/values.yaml
This pr allows to configure the http port on which tracetest will listen, and set the deployment accordingly
-
-
-
> Tracetest: add httpPort config

- charts/testkube-api/templates/role.yaml
Remove version from apiGroup in ClusterRole
-
- Rename api groups
- TestKube API erroring with insufficient permissions to watch resources
> feat: fix wrong testkube operator rbac

- charts/testkube-api/templates/role.yaml
Fixes issue with testkube trigger api returning errors due to no permissions to list namespaces
-
-
- Issue with testkube trigger api returning errors due to no permissions to list namespaces
> testkube-api: add namespaces to watcher role for API RBAC

- .github/workflows/helm-deploy-testkube-charts-stage.yaml
- tests checkout from main `testkube` repo
- executor tests - test delete, create, and schedule checks for all executor tests
- (re)creating Postman sanity test (with testkube cli) + running `Test` - updated
- (re)creating Dashboard E2E tests (from CRD)
- Running Staging testsuite
- Postman and Dashboard tests creation is separated on purpose to check creation from CLI and CRD
- Postman Test isn't included in Staging testsuite to check both running a single test and testsuite
- kubectl delete changed from `|| true` to `--ignore-not-found=true`
Merge after:
> Testkube - staging tests

- .github/workflows/helm-releaser-testkube-charts.yaml
Tests similar to the ones in staging workflow (https://github.com/kubeshop/helm-charts/pull/315)
- tests checkout from main testkube repo
- executor tests - test create/update, and schedule checks for all executor tests
- (re)creating Dashboard E2E tests (from CRD)
- Running Demo testsuite
- Postman and Dashboard tests creation is separated on purpose to check creation from CLI and CRD
- Postman Test isn't included in Demo testsuite to check both running a single test and testsuite
- kubectl delete changed from || true to --ignore-not-found=true
**Merge after:**
> chore: Testkube tests - dev/demo workflow

- charts/testkube/values.yaml
Removed ingress annotations from values file so that they won't appear if users create a different type of ingress, except for nginx.
> remove ingress annotations; added examples instead

- charts/testkube-operator/templates/deployment.yaml
- charts/testkube-operator/values.yaml
- charts/testkube/Chart.yaml
- charts/testkube/templates/pre-upgrade.yaml
- charts/testkube/values.yaml
- upgrade NATS to `0.19.1` to include latest chart version;
- moved `webhook` image to kubeshop repository;
- added option to disable `mongo` upgarde.
Might be NATS upgrade, but it was tested.
> nat chart update

- charts/testkube-dashboard/templates/oauth2-service.yaml
- charts/testkube-dashboard/values.yaml
- charts/testkube/values.yaml
We need to change the oauth2 service type from ClusterIP to NodePort in GKE. So values should have it.
-
-
-
> adding .Values.oauth2.serviceType

- .github/workflows/helm-deploy-testkube-charts-stage.yaml
- .github/workflows/helm-releaser-testkube-charts.yaml
- charts/testkube/Chart.yaml
Bitnami uses a rotation script that cleans `index.yaml` file entries older than 6 months. The whole `index.yaml` is being generated and stored in GitHub. So if we want to keep using older versions for MongoDB we need to replace the existing repository (by default the one truncated every 6 months) with the path to the full file hosted in GitHub:
Replace this URL:
`repository: https://charts.bitnami.com/bitnami`
with this:
`repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami`
See the FAQ for this:  https://github.com/bitnami/charts/issues/10833
-
-
-
> Update bitmani repo

- charts/tracetest/templates/deployment.yaml
- charts/tracetest/templates/service.yaml
We need to expose the otlp ports from both the container and the service so the otel collector can reach out to tracetest.
-
- Exposing tracetest otlp ports
- [[In-App Config] Installer Changes#1630](https://github.com/kubeshop/tracetest/issues/1630)
> feature(tracetest): allowing otlp access

- charts/testkube-api/templates/minio.yaml
- charts/testkube-api/values.yaml
- charts/testkube/values.yaml
By default the minio pods will wait 120 seconds (2 minutes) before Kubernetes starts checking their readiness. This change allows the user to change this initial wait value but keeps the existing default.
Background: Waiting for 2 minutes before marking the Pods as ready slows down the startup on local deployments i.e. KinD
> Allow the Liveness and Readiness Probe Initial Delay to be configured (default to existing value of 120 seconds)

- .github/workflows/helm-deploy-testkube-charts-stage.yaml
mongodb CPU resource usage is very high in chart 12.0.0. As a workaround we disable `liveness` and `readiness` probes to avoid that. Now it's using around `255m` of CPU and  `342Mi` of memory
-
-
-
> disable mongo probes for stage

- charts/testkube-dashboard/templates/deployment.yaml
- charts/testkube-dashboard/values.yaml
Add `containerPort` var so that it won't be changed when we update service port definition. 
-
-
-
> add container port var

- charts/testkube/values.yaml
Since we always put `/results/v1` path as API enpoint in Dashboard UI I think it'll be clearer for the users to put the same in the `values.yaml` file. Moreover, `*` is not accepted by AWS Ingress Controller and gives an error during deployment, so the users have to update it manually and for some of them it is quite challenging and requires much time. 
-
-
-
> update path for api

- charts/testkube-api/templates/deployment.yaml
- charts/testkube-api/values.yaml
- charts/testkube/values-demo.yaml
- charts/testkube/values-stage.yaml
- charts/testkube/values.yaml
This allows the configuration of custom liveness and readiness probes for the testkube-api
No breaking changes.
- Templated liveness and readiness probes in testkube-api deployment to allow custom values
#417
> feat: allow custom probes for testkube-api (#417)

- charts/testkube-operator/templates/rolebinding.yaml
Fixes the RoleBinding refs to Roles to match the correct names, in testkube-operator
No breaking changes.
* Change names of RoleBinding/ClusterRoleBinding references for roles "-operator-manager-role" , "-operator-proxy-role" and "-operator-leader-election-role"
-
> fix:rolebinding references to match role names in operator

- charts/testkube-api/templates/serviceaccount.yaml
The `vaules.yaml` file for the kubetest-api chart allows for annotations to be set of the kubetest-api serviceAccount [here](https://github.com/kubeshop/helm-charts/blob/d861b662f38741c6ebfd8c1f4f8a711f8314a2ec/charts/testkube-api/values.yaml#L161) but as best I can tell they are never added to the serviceAccount.
This change copies the logic for setting serviceAccount annotations from the testkube-dashboard chart.
The ability to add an annotation to the testkube-api SA is important if you want to be able to direct testkube-api to use S3 storage instead of Minio.
https://docs.testkube.io/concepts/common-issues/#installation-with-s3-storage-and-iam-authentication
-
-
- Adds missing support for setting annotations on the testkube-api serviceAccount
> Support adding annotations to the kubetest-api SA

- charts/testkube/templates/pre-upgrade-sa.yaml
Before:
``` 
$ helm lint 
==> Linting .
[INFO] Chart.yaml: icon is recommended
[ERROR] templates/pre-upgrade-sa.yaml: unable to parse YAML: invalid Yaml document separator: kind: Role
[ERROR] templates/pre-upgrade-sa.yaml: unable to parse YAML: invalid Yaml document separator: apiVersion: rbac.authorization.k8s.io/v1
Error: 1 chart(s) linted, 1 chart(s) failed
``` 
After
``` 
helm lint 
==> Linting .
[INFO] Chart.yaml: icon is recommended
1 chart(s) linted, 0 chart(s) failed
``` 
See https://github.com/helm/helm/issues/10149#issuecomment-929205040
-
-
-
> fix: lint error for testkube chart

- charts/testkube-dashboard/templates/oauth2-deployment.yaml
- charts/testkube-dashboard/values.yaml
- charts/testkube/values.yaml
Added an option to specify volumes for oauth2 deployment, as requested in [issue](https://github.com/kubeshop/helm-charts/issues/447).
-
-
-
> option to add volumes

- charts/testkube-operator/templates/pre-upgrade.yaml
- charts/testkube-operator/values.yaml
pre-upgrade job image wasn't configurable. It was reported on #457 
-
-
-
> Configure pre-upgrade image

- charts/tracetest/templates/deployment.yaml
Fixes the Tracetest heml charts as the expected value is a string but we are passing it as boolean
-
-
- Fixes the Tracetest heml charts as the expected value is a string but we are passing it as boolean
> adding missing quotes for the TRACETEST_DEV env variable

- charts/testkube-operator/templates/pre-upgrade-sa.yaml
- charts/testkube-operator/templates/pre-upgrade.yaml
Fixes the naming of pre-upgrade operator resources to be more descriptive and avoid issues with other resources in the cluster due to naming collision. 
-
-
-
> fix:clear naming in operator pre upgrade resources

- charts/testkube-operator/templates/pre-upgrade-sa.yaml
- charts/testkube-operator/templates/pre-upgrade.yaml
- charts/testkube-operator/values.yaml
Allow configuring imagePullSecret in upgrade operator jobs and consistency changes to match other upgrade jobs
match configuration with:
https://github.com/kubeshop/helm-charts/blob/main/charts/testkube/templates/pre-upgrade.yaml
-
-
-
> fix: allow configuring imagePullSecret in upgrade operator jobs

- charts/tracetest/templates/service.yaml
- charts/tracetest/values.yaml
This PR fixes the HTTP port that the internal OTLP Server uses on Tracetest.
- https://github.com/kubeshop/tracetest/issues/2143
> Fix Tracetest OTLP Server port

- charts/testkube-api/executors.json
- charts/testkube-api/job-container-template.yml
- charts/testkube-api/job-scraper-template.yml
- charts/testkube-operator/templates/executor.testkube.io_executors.yaml
- charts/testkube-operator/templates/tests.testkube.io_tests.yaml
> feat: deprecate args

- .github/workflows/helm-deploy-testkube-charts-develop.yaml
- .github/workflows/helm-deploy-testkube-charts-stage.yaml
Re-work flow to deploy api and executors together
-
-
-
> rework flow to deploy executors with api

- charts/tracetest/Chart.yaml
- charts/tracetest/templates/ingress.yaml
On #487 we centralized the Tracetest port configuration on `.Values.server` config, removing the duplicate info on `.Values.service`. However, when we did that we forgot to fix this information on the ingress controller. This PR aims to to that, changing the controller to use `.Values.server.httpPort`.
- Tracetest ingress controller
> Fix tracetest ingress configuration

- charts/tracetest/Chart.yaml
- charts/tracetest/values.yaml
This PR upgrades postgres image tag to v14.7.0, which is the closest version that proves ARM64 docker images. This fixes https://github.com/kubeshop/tracetest/issues/2491
-
-
-
> [tracetest]  upgrade postgres version

- charts/testkube-api/templates/deployment.yaml
- charts/testkube-api/values.yaml
Set a sensible default for API server HTTP Read buffer size
Avoid explicit use of the following when using oauth2-proxy in front of api server
``` 
testkube-api:
extraEnvVars:
- name: APISERVER_HTTP_READBUFFERSIZE
value: "8192"
``` 
Relates to https://github.com/kubeshop/testkube/issues/2870
-
-
-
> Set a sensible default for API server HTTP Read buffer size

- charts/testkube-api/templates/deployment.yaml
Added `quote` function to convert api vars from number to string, because the deployment failed with the error:
```
json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
```
-
-
-
> fix: convert the var to string

- charts/testkube-api/templates/servicemonitor.yaml
Fix service monitor target port
api-server listens on locahost:8088/metrics but service monitor was scraping localhost:80/metrics
-
-
Before the fix
After the fix
-
> fix: testkube service monitor target port

- charts/testkube-operator/templates/tests.testkube.io_tests.yaml
Doc: refine schema for content.type
Extracted from https://github.com/kubeshop/testkube/blob/cca3c13629078891f269f691e1050ae5adb99d5a/docs/docs/test-types/prebuilt-executor.md?plain=1#L60-L65
-
-
-
> Testkube Doc: refine  test doc for content.type

- charts/testkube-operator/templates/tests.testkube.io_tests.yaml
Pods can't use secrets from a different namespace as env vars as explained in issue [#4308](https://github.com/kubeshop/testkube/issues/4038). This PR removes the namespace key from the CRD.
I am in doubt whether or not this is all that is required to remove it, so thoughts are welcomed about this.
-
Removed namespace from tokenSecret and usernameSecret from `tests.testkube.io_tests.yaml` CRD
-
-
> testkube-operator: Removed ns from tokenSecret and usernameSecret

- charts/testkube-operator/templates/tests.testkube.io_tests.yaml
- charts/testkube-operator/templates/tests.testkube.io_testsources.yaml
> feat: post run script field

- charts/testkube-api/templates/deployment.yaml
- charts/testkube-api/templates/minio.yaml
- charts/testkube-api/values.yaml
- charts/testkube/values.yaml
Added an option to retrieve Minio credentials and Mongo SSL certificate data from k8s secrets. 
-
-
-
> feat: update referencing of secrets in minio and TK API

- .github/workflows/helm-releaser-testkube-main-chart-only.yaml
Added release notes generation to main chart flow that bumps vesrion when we make a change to any manifest in helm-chart.
-
-
-
> ci: add release notes generation

- charts/testkube-api/slack-template.json
- charts/testkube-api/templates/deployment.yaml
- charts/testkube-api/values.yaml
- charts/testkube/README.md
- charts/testkube/values-demo.yaml
- charts/testkube/values-develop.yaml
- charts/testkube/values-pre-release.yaml
- charts/testkube/values-stage.yaml
- charts/testkube/values.yaml
> feat: cluster name parameter

- charts/testkube-api/templates/minio.yaml
Revert logic for passing secrets for minio, since it breaks feature https://github.com/kubeshop/testkube/issues/3965
-
-
-
> fix: revert logic for secrets in minio

- charts/tracetest/templates/_helpers.tpl
- charts/tracetest/templates/deployment.yaml
- charts/tracetest/values.yaml
On this PR, we detect if the user defines the variable `server.pathPrefix` on the helm chart and update the livenessProbe and readinessProbe to consider it.
Loom: https://www.loom.com/share/110b45511ece468191b5be61bb79ee91?sid=af66b2a9-c819-451e-a956-313683ad013c
- Changed tracetest deployment.yaml to consider pathPrefix variable on probes
> fix(chart/tracetest): update probes configuration on Tracetest to consider pathPrefix config

- .github/workflows/helm-releaser-testkube-main-chart-only.yaml
- scripts/main_chart_releaser.sh
Updated script to bump versions of ALL sub-charts, not only the main one - `testkube`, when we merge a new feature. This is to prevent issues described [here](https://github.com/kubeshop/helm-charts/issues/590).
-
-
-
> fix: update releaser script

- .github/workflows/helm-releaser-testkube-main-chart-only.yaml
- scripts/main_chart_releaser.sh
revert changes as bumping version of sub-charts makes deployment fail.
-
-
-
> revert changes

- charts/testkube-dashboard/templates/deployment.yaml
- charts/testkube-dashboard/values.yaml
- charts/testkube/values.yaml
Allow user-specified value to override `REACT_APP_ROOT_ROUTE` reliably
-
- Use user-provided value for `REACT_APP_ROOT_ROUTE` when provided in `.Values.proxyPrefix` (this name was chosen in line with the oauth2-proxy argument name).  Fallback to using `.Values.ingress.path`
- #613
> fix: Allow override of REACT_APP_ROOT_ROUTE with proxyPrefix

- charts/testkube-dashboard/templates/oauth2-deployment.yaml
- charts/testkube-dashboard/values.yaml
- charts/testkube/values.yaml
Allow reference of Secret or ConfigMap to provide multiple environment variables. This allows deployers of the Helm Chart to manage multiple sensitive or non-sensitive values without needing to override or modify multiple default values.
- None
- Allow extension of oauth2-proxy deployment with prexisting Secret or Configmap
- #611
> feat: Allow extension of oauth2-proxy environment variables with envFrom

- charts/testkube/values-demo.yaml
- charts/testkube/values-develop.yaml
- charts/testkube/values-stage.yaml
Add node selectors for the core TK services.
-
-
-
> Values: add node selectors

- charts/testkube/templates/pre-upgrade.yaml
- charts/testkube/values.yaml
Fix for https://github.com/kubeshop/helm-charts/issues/624. Adds the ability to set the annotations on the pre upgrade mongo upgrade job.
-
-
-
> Add ability to set pod annotations on mongo upgrade job

- charts/tracetest/templates/configmap.yaml
- charts/tracetest/templates/deployment.yaml
- charts/tracetest/values.yaml
This PR removes old configs from our charts (`analytic ` and `pollingProfile` that where moved to the Resources API) and adds a new way to inject env vars on Tracetest, which can help us to update its internal configuration.
1. Go to the `./charts` folder
2. Run the command: 
```sh
helm template tracetest ./tracetest --values ./tracetest/values.yaml
```
3. At the output, you should see the Tracetest deployment with the following config:
```yaml
---
apiVersion: apps/v1
containers:
- name: tracetest
securityContext:
{}
image: "kubeshop/tracetest:v0.13.8"
env:
- name: TRACETEST_DEV
value: "false"
```
> chore(charts/tracetest): update the way to inject env vars on Tracetest chart

- charts/tracetest/Chart.yaml
- charts/tracetest/templates/configmap.yaml
Add an option to avoid installing postgres with tracetest.
1. Go to the `./charts` folder
2. Run the command: 
```sh
helm template tracetest ./tracetest --values ./tracetest/values.yaml
```
3. At the output, you should see the Tracetest deployment with a postgres installation normally.
1. Create a `values.yaml` file with the following options:
```yaml
postgresql:
enabled: false
environmentVars:
- name: TRACETEST_TESTPIPELINES_TRIGGEREXECUTE_ENABLED
value: "false"
- name: TRACETEST_TESTPIPELINES_TRACEFETCH_ENABLED
value: "false"
- name: TRACETEST_POSTGRES_DBNAME
value: "tracetest"
- name: TRACETEST_POSTGRES_HOST
value: "10.92.0.3"
- name: TRACETEST_POSTGRES_USER
value: "my-user"
- name: TRACETEST_POSTGRES_PASSWORD
value: "my-password"
- name: TRACETEST_POSTGRES_PORT
value: "5432"
```
2. Go …
> chore(tracetest): adding option to disable pg installation

- charts/testkube-api/templates/deployment.yaml
- charts/testkube-api/values.yaml
We manage our applications using GitOps. Directly referencing a value from helm values would require us to place the secrets into Git. To resolve this, we will manage the secret using external-secret and make testkube reference that secret.
Add helm values to use cloud properties from existing secret instead of helm values
-
-
-
> Add helm values to read cloud properties from existing secret

- charts/testkube/Chart.yaml
- charts/testkube/templates/pre-upgrade.yaml
- charts/testkube/values.yaml
Upgrade Mongo to 6.0.5
Image: docker.io/zcube/bitnami-compat-mongodb:6.0.5-debian-11-r64 (supports ARM and AMD)
Chart version: mongodb-13.10.1 (released on 27 Apr, 2023)
-
-
> build: mongo upgrade to app version 6.0.5

- charts/testkube-api/README.md
- charts/testkube-api/templates/deployment.yaml
- charts/testkube-api/values.yaml
- charts/testkube/README.md
- charts/testkube/values-demo.yaml
- charts/testkube/values-develop.yaml
- charts/testkube/values-stage.yaml
- charts/testkube/values.yaml
> fix: enable secrets endpoint

- charts/testkube-operator/templates/deployment.yaml
- charts/testkube-operator/values.yaml
Adding nats to the operator for publishing events
-
-
-
> feat: add nats endpoint to operator

- charts/tracetest/templates/_helpers.tpl
- charts/tracetest/templates/configmap.yaml
- charts/tracetest/templates/deployment.yaml
- charts/tracetest/values.yaml
Add an option to override the referenced configmap name. This allows for users to create a custom configmap externally and reference it in this chart.
> feat(tracetest): allow configMapOverride

- charts/testkube-dashboard/templates/hpa.yaml
There is a bug that makes syncing hpa fail. As a workaround we get switch places between cpu and memory: https://github.com/argoproj/argo-cd/issues/1079#issuecomment-463849329
-
-
-
> fix: sync hpa with argocd

- charts/tracetest/Chart.yaml
- charts/tracetest/templates/_helpers.tpl
- charts/tracetest/templates/configmap.yaml
- charts/tracetest/values.yaml
This PR allows to configure an external postgres database more easily. To do so, users need to disable the dependent chart and set the correct hostname. Example `values.yaml` file:
```yaml
postgres:
enabled: false # disable the postgres chart install
auth:
host: mypg.example.com #this is a new parameter
username: myuser
password: mypass
```
The behavior of the `ConfigMap` was changed: Before, it would not include the postgres settings if the chart was disabled. Now we always include them.
> [tracetest] feat: allow configuring external postgres

- charts/testkube-operator/templates/deployment.yaml
- charts/testkube-operator/values.yaml
This reverts commit 613e3d824ebf93a103e5b7ee3cf7f3e5a6b8d4b9.
-
-
-
> fix: remove nats from the operator TKC-631

- charts/testkube/README.md
- charts/testkube/values.yaml
fixes https://github.com/kubeshop/helm-charts/issues/686
- Remove tolerations from testkube-operator since proxy image doesn't support arm64 nodes
- https://github.com/kubeshop/helm-charts/issues/686
> fix: Remove tolerations from testkube-operator since proxy image doesn't support arm64 nodes

- charts/testkube-api/templates/ui-ingress.yaml
- charts/testkube-api/values.yaml
- charts/testkube-dashboard/templates/ingress.yaml
- charts/testkube-dashboard/values.yaml
closes #709
Changes Ingress for testkube api and testkube dashboard ingress pathtype
-
-
-
> fix: allow setting pathtype for testkube api and dashboard ingress

- charts/testkube-api/templates/role.yaml
Allows test pods to query the metrics.k8s.io API. This is especially handy since it allows for a curl executor to query metrics-server in order to ensure metrics are being collected for the pod. This makes no attempt to handle or provide for authentication (possible via the service account's token). This simply handles the authorization piece.
- None
-
-
> feat: Grant read access to metrics.k8s.io API

- charts/testkube/templates/pre-upgrade-sa.yaml
- charts/testkube/templates/pre-upgrade.yaml
Disable mongo pre-upgrade job if MongoDB is disabled.
-
-
-
> feat: [TKC-1455] disable mongo pre-upgrade job if mongodb is disabled

- charts/testkube-api/templates/deployment.yaml
Renamed TESTKUBE_PRO_TLS_INSECURE to TESTKUBE_CLOUD_TLS_INSECURE as it was not used by the application. 
-
-
-
> fix: rename cloud tls var name

- charts/testkube-api/templates/role.yaml
- charts/testkube-operator/templates/role.yaml
- charts/testkube-operator/templates/rolebinding.yaml
* Add missing permission for ConfigMaps `deletecollection` (for bulk cleanup of TestWorkflows resources)
* Add TestWorkflow permissions for `testkube-operator`
> fix: add missing roles for TestWorkflows

- charts/testkube-operator/templates/role.yaml
Used `Role` instead of `ClusterRole` for operator's RBAC
> fix: typo - Role instead of ClusterRole

- .github/workflows/lint.yaml
- charts/testkube-operator/templates/webhook.yaml
- charts/testkube-operator/values.yaml
- charts/testkube/values.yaml
Cherry-pick to main.
* add an option to provide nameselector and scope in operator webhook
-
-
-
> feat: add an option to provide nameselector and scope in operator webhook

- charts/testkube/Chart.yaml
- charts/testkube/values.yaml
This pull request takes care of adding support for overriding the NATS subcharts image options i.e. enabling users to explicitly set repository, tag, pull policy, and registry for each of the images utilized (NATS server, NATS config reloader, and NATS Box).
It looks like NATS Box is due to be disabled in the near future but it may be useful to have support for this in the meantime until it is fully disabled, at which point this NATS Box image override logic could be removed. I have also not included override support for the NATS Prometheus exporter as it looks like this is not currently in use.
N/A
-
Includes addition of commented out block to allow users to override NATS subchart image settings when required.
-
N/A
-
> Feature: Add support for overriding NATS image options

- charts/testkube-operator/Chart.yaml
- charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
- charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml
- charts/testkube/Chart.yaml
* Add `run.shell` option, that will be similar as direct `shell` operation
* operator: https://github.com/kubeshop/testkube-operator/pull/238
- https://linear.app/kubeshop/issue/TKC-1808/[testworkflows]-add-runshell-option
> feat(TKC-1808): allow to pass `run.shell` for TestWorkflow commands

- charts/testkube-api/templates/_helpers.tpl
- charts/testkube-api/templates/deployment.yaml
- charts/testkube-api/values.yaml
- charts/testkube/values.yaml
https://linear.app/kubeshop/issue/TKC-1851/[workday]-issue-configuring-testworkflows-to-use-private-registry
-
-
-
> fix: [TKC-1851] Add registry configuration for workflows docker images

- charts/testkube-api/templates/deployment.yaml
It allows defining values.yaml that can be installed in arbitrary namespaces without reconfiguration.
```
url: testkube-enterprise-api.{{.Release.Namespace}}.svc.cluster.local:8089
``` 
-
-
-
> chore: template url values

- charts/testkube-api/job-container-template.yml.tmpl
- charts/testkube-api/job-scraper-template.yml.tmpl
- charts/testkube-api/job-template.yml.tmpl
- charts/testkube-api/slave-pod-template.yml.tmpl
Only covers pre-built and container executors.
-
- Fix job templates to be able to pull from Git repositories using private-CAs. Covers prebuilt and container executors only, not workflows.
- TKC-1901
- TKC-1911
> fix: pull from git server with private-ca certs

- charts/testkube-api/templates/role.yaml
- charts/testkube/values-demo.yaml
- charts/testkube/values-develop.yaml
- charts/testkube/values-stage.yaml
* feat: use same ServiceAccount for Tests as for TestWorkflows (#847)
(cherry picked from commit fe154b9b83c2250dd651c88aadd4c268210b218c)
> release: default service account for testworkflows

- charts/testkube-api/templates/role.yaml
```
{"level":"warn","ts":1716289269.2448988,"caller":"imageinspector/inspector.go:73","msg":"error while saving image details in the cache","registry":"","image":"bitnami/minio","error":"configmaps \"testkube-image-cache\" is forbidden: User \"system:serviceaccount:testkube:testkube-api-server-tests-job\" cannot patch resource \"configmaps\" in API group \"\" in the namespace \"testkube\""}
```
> fix: add missing patch/update permissions (required for updating ConfigMap of image inspector

- charts/testkube-api/templates/rolebinding.yaml
Some RoleBindings were generated when the following was set `rbac.create: false`:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
name: testexecutions-crb-release-name
labels:
app.kubernetes.io/version: "1.17.39"
helm.sh/chart: testkube-api-1.17.39
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: api-server
app.kubernetes.io/instance: release-name
wd_service: testkube
roleRef:
apiGroup: rbac.authorization.k8s.io
kind: Role
name: testexecution-role-release-name
subjects:
- kind: ServiceAccount
name: testkube-api-server
namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
name: testsuiteexecutions-crb-release-name
labels:
app.kubernetes.io/version: "1.17.39"
helm.sh/chart: testkube-api-1.17.39 …
```
> fix: testkube-api: fix issue with generating rolebindings if rbac is disabled

- charts/testkube-api/templates/testworkflows/builtin-templates/beta/artillery.yaml
- charts/testkube-api/templates/testworkflows/builtin-templates/beta/cypress.yaml
- charts/testkube-api/templates/testworkflows/builtin-templates/beta/gradle.yaml
- charts/testkube-api/templates/testworkflows/builtin-templates/beta/jmeter.yaml
- charts/testkube-api/templates/testworkflows/builtin-templates/beta/k6.yaml
- charts/testkube-api/templates/testworkflows/builtin-templates/beta/maven.yaml
- charts/testkube-api/templates/testworkflows/builtin-templates/beta/playwright.yaml
- charts/testkube-api/templates/testworkflows/builtin-templates/beta/postman.yaml
Because of `PATCH` the beta templates need to be specifically disabled - otherwise this label won't be removed and they will still be visible.
> feat: Testkube workflow templates - disable beta templates in wizard

- charts/testkube-api/templates/_helpers.tpl
- charts/testkube-api/templates/_job-container-template.yaml.tpl
- charts/testkube-api/templates/_job-scraper-template.yaml.tpl
- charts/testkube-api/templates/_job-template.yaml.tpl
- charts/testkube-api/templates/_slave-pod-template.yaml.tpl
- charts/testkube-api/templates/deployment.yaml
- charts/testkube-api/values.yaml
- charts/testkube/README.md
- charts/testkube/values.yaml
CHANGELOG:
* add support for global volume mounts (mounted to both API and Test Jobs)
* add support for defining global CA cert path
* fix issue with scraper being disabled in agent mode
Example how to inject CA cert:
```
global:
tls:
caCertPath: /etc/testkube/certs
volumes:
additionalVolumes:
- name: custom-ca
secret:
secretName: custom-cert
additionalVolumeMounts:
- name: custom-ca
mountPath: /etc/testkube/certs
readOnly: true
```
-
-
-
> testkube: add support for global mounting of volumes

- .github/sandbox-comment-template.md
- .github/workflows/dispatch-sandbox-push.yaml
- add outputs with sandbox endpoints to a CI run;
- post outputs on a sandnox PR as a comment
-
-
-
> ci: add outputs to sandbox

- charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
- charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml
* https://github.com/kubeshop/testkube-operator/pull/293
- https://linear.app/kubeshop/issue/TKC-2372/workflows-istio-support-phase-2
> feat: update CRD - add options to control Test Workflow orchestration

- charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowexecutions.yaml
- charts/testkube-operator/templates/testworkflows.testkube.io_testworkflows.yaml
- charts/testkube-operator/templates/testworkflows.testkube.io_testworkflowtemplates.yaml
> chore: sync workflows tags from operator

- charts/tracetest/templates/configmap.yaml
This PR fixes a bug on the chart causing provisioning to not work. It was failing with this message: 
```
2024/09/09 16:17:45 [provisioning] attempting file:  /app/config/provisioning.yaml
2024/09/09 16:17:45 [provisioning] error: cannot unmarshal yaml for provisioning file: [1:1] scalar was used where mapping is expected
>  1 | |
^
```
The issue was caused by an incorrect usage of a value in the configmap template, causing the provisioning file to look like this:
```yaml
apiVersion: v1
data:
config.yaml: |-
provisioning.yaml: |-
| # this line here was the issue
---
type: DataStore
spec:
name: Jaeger
type: jaeger
jaeger:
endpoint: jaeger-query:16685
tls:
insecure: true
---
type: PollingProfile
spec:
name: Custom Profile
strategy: periodic
default: true
periodic:
timeout: 30s
retryDelay: …
```
> fix(tracetest): fix provisioning importing in configmap

- charts/testkube-api/templates/deployment.yaml
* after https://github.com/kubeshop/testkube/pull/5866 we will be streaming logs through the file system
* to ensure that it won't break for Users who have `readOnlyRootFilesystem`, we should mount it there
> fix: add /tmp as a volume to the API Server

- charts/testkube-api/README.md
- charts/testkube-api/templates/testworkflows/builtin-templates/global-template.yaml
- charts/testkube-api/values.yaml
- charts/testkube/README.md
- charts/testkube/values.yaml
```yaml
global:
globalTemplate:
enabled: true
external: true
name: my-own-global-template
```
* https://linear.app/kubeshop/issue/TKC-2614
> feat: add support for external global template

- charts/testkube-api/README.md
- charts/testkube-api/templates/deployment.yaml
- charts/testkube-api/values.yaml
- charts/testkube/README.md
- charts/testkube/values-demo.yaml
- charts/testkube/values-develop.yaml
- charts/testkube/values-stage.yaml
- charts/testkube/values.yaml
> feat: [TKC-2622] container env var

- .github/workflows/helm-deploy-testkube-charts-develop-commit.yaml
- .github/workflows/helm-deploy-testkube-charts-develop.yaml
- .github/workflows/helm-releaser-testkube-charts.yaml
- .github/workflows/helm-releaser-testkube-main-chart-only.yaml
- scripts/chart_releaser.sh
- scripts/main_chart_releaser.sh
> ci: update actions

- charts/testkube/values.yaml
> charts: provide example for nats chart

- charts/testkube-api/templates/deployment.yaml
- charts/testkube-api/templates/service.yaml
- charts/testkube-api/values.yaml
- charts/testkube/values-demo.yaml
- charts/testkube/values-develop.yaml
- charts/testkube/values-stage.yaml
- charts/testkube/values.yaml
* https://github.com/kubeshop/testkube/pull/5957
> feat: support Control Plane for OSS Agent

- charts/testkube-api/templates/deployment.yaml
- charts/testkube-api/values.yaml
- charts/testkube/values-demo.yaml
- charts/testkube/values-develop.yaml
- charts/testkube/values-stage.yaml
- charts/testkube/values.yaml
> chore: improve startup time

- charts/testkube-api/templates/_helpers.tpl
- charts/testkube-api/templates/deployment.yaml
- charts/testkube-api/templates/minio.yaml
- charts/testkube-api/values.yaml
- charts/testkube-logs/templates/_helpers.tpl
- charts/testkube-logs/templates/deployment.yaml
- charts/testkube-logs/values.yaml
- charts/testkube-operator/templates/_helpers.tpl
- charts/testkube-operator/templates/deployment.yaml
- charts/testkube-operator/templates/webhook-cert-create.yaml
- charts/testkube-operator/templates/webhook-cert-patch.yaml
- charts/testkube-operator/values.yaml
- charts/testkube/Chart.yaml
- charts/testkube/charts/nats/Chart.yaml
- charts/testkube/charts/nats/files/nats-box/deployment/container.yaml
- charts/testkube/charts/nats/files/nats-box/deployment/pod-template.yaml
- charts/testkube/charts/nats/files/stateful-set/nats-container.yaml
- charts/testkube/charts/nats/files/stateful-set/pod-template.yaml
- charts/testkube/charts/nats/files/stateful-set/prom-exporter-container.yaml
- charts/testkube/charts/nats/files/stateful-set/reloader-container.yaml
- charts/testkube/charts/nats/templates/_helpers.tpl
- charts/testkube/charts/nats/values.yaml
- charts/testkube/values.yaml
Add an option to provide `global.securityContext` to all charts.
-
-
-
> feat: add global security context

- charts/testkube-api/README.md
- charts/testkube-api/templates/cli-ingress.yaml
- charts/testkube-api/values.yaml
- charts/testkube/README.md
- charts/testkube/values.yaml
* https://github.com/kubeshop/helm-charts/pull/956#issuecomment-2469991019
> fix: add back CLI Ingress

- charts/testkube-api/templates/deployment.yaml
- charts/testkube-logs/templates/deployment.yaml
The current indentation is set to 6 which places the value on the same level as the tolerations: or the nodeSelector:
-
-
-
> indent to 8 for tolerations and nodeSelector

- charts/testkube-api/templates/role.yaml
- charts/testkube-api/templates/rolebinding.yaml
- charts/testkube-operator/templates/executor.testkube.io_webhooks.yaml
- charts/testkube-operator/templates/executor.testkube.io_webhooktemplates.yaml
- charts/testkube-operator/templates/role.yaml
> feat: [TKC-2933] add webhook config

- charts/testkube-api/templates/deployment.yaml
* Fix for https://github.com/kubeshop/helm-charts/pull/985
* Ignore when `inline: true` without `spec`
> fix: allow lack of global template

- charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml
> feat: [TKC-3146] [TKC-3147] trigger parameters and regex

- charts/testkube-api/templates/_executors.json.tpl
- charts/testkube-api/values.yaml
- charts/testkube/values.yaml
We stop building executors' images so it's necessary pin a specific tag for the executors. 
-
-
-
> update executors image tag with a specific version

- charts/testkube/values.yaml
Testkube chart was missing a property in its values.yaml file that allow users to install agent using an existing secret to manage key, orgId, and envId param needed to connect agent with a Control Plane.
-
-
- Add existingSecret property from testkube-api into the umbrella chart values.yaml file.
> fix: add missing property in the testkube umbrella chart

- charts/testkube-runner/templates/deployment.yaml
Name of the runner volume do not support uppercase, fixing to match with kubernetes convention.
-
-
- testkube runner volumen name
> fix: testkube runner volumen name

- charts/testkube-api/templates/deployment.yaml
- charts/testkube-api/values.yaml
- charts/testkube/Chart.yaml
- charts/testkube/values.yaml
Tweaks the charts to prevent deployment of the `operator` whilst simultaneously enabling the controllers ported to the `agent`.
Waiting on:
- https://github.com/kubeshop/testkube/pull/6386
- https://github.com/kubeshop/testkube-operator/pull/330
> feat: Enable Agent based Executor controllers

- charts/testkube-runner/templates/deployment.yaml
- charts/testkube-runner/values.yaml
Add extra values that allow for the creation and registering of a runner in a single `helm install` step. Using the new values it would be possible using a command similar to:
```
helm install my-testkube-runner kubeshop/testkube-runner \
--set runner.register.token="tkcapi_5f4dcc3b5aa765d61d8327deb882" \
--set runner.orgId="tkcorg_97c6968d0a9e7880"
```
Requires changes in https://github.com/kubeshop/testkube/pull/6410 otherwise nothing will happen.
> feat: Enable runner self-registration
